# Code generated by pangea-forge.
# InSpec profile for verifying google_network_security_authz_policy infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GOOGLE_TOKEN and GOOGLE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/google_network_security_authz_policy/ -t google://

control 'google_network_security_authz_policy-exists' do
  impact 1.0
  title 'Manages a google_network_security_authz_policy resource'
  desc 'Verify that the google_network_security_authz_policy resource exists and has expected properties'

  describe google_network_security_authz_policy(name: attribute('id')) do
    it { should exist }
    its('action') { should_not be_nil }
    its('location') { should_not be_nil }
    its('name') { should_not be_nil }
    its('target') { should_not be_nil }
  end
end
