# Code generated by pangea-forge.
# InSpec profile for verifying google_netapp_host_group infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GOOGLE_TOKEN and GOOGLE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/google_netapp_host_group/ -t google://

control 'google_netapp_host_group-exists' do
  impact 1.0
  title 'Manages a google_netapp_host_group resource'
  desc 'Verify that the google_netapp_host_group resource exists and has expected properties'

  describe google_netapp_host_group(name: attribute('id')) do
    it { should exist }
    its('hosts') { should_not be_nil }
    its('location') { should_not be_nil }
    its('name') { should_not be_nil }
    its('os_type') { should_not be_nil }
    its('type') { should_not be_nil }
  end
end
