# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class ContainerAnalysisOccurrenceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :attestation, T::Array.of(T::Hash)
    attribute :note_name, T::String
    attribute :resource_uri, T::String
    attribute? :remediation, T::String.optional
  end
end
