# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class DataCatalogTaxonomyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :display_name, T::String
    attribute? :activated_policy_types, T::Array.of(T::String).optional
    attribute? :description, T::String.optional
  end
end
