# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_dataplex_task/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleDataplexTask
    include Pangea::Resources::ResourceBuilder

    define_resource :google_dataplex_task,
      attributes_class: Google::Types::DataplexTaskAttributes,
      outputs: { id: :id },
      map: [:execution_spec, :trigger_spec],
      map_present: [:description, :display_name, :labels, :lake, :location, :notebook, :spark, :task_id]
  end
  module Google
    include GoogleDataplexTask
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
