# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class DataplexTaskAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :execution_spec, T::Array.of(T::Hash)
    attribute :trigger_spec, T::Array.of(T::Hash)
    attribute? :description, T::String.optional
    attribute? :display_name, T::String.optional
    attribute? :labels, T::Hash.optional
    attribute? :lake, T::String.optional
    attribute? :location, T::String.optional
    attribute? :notebook, T::Array.of(T::Hash).optional
    attribute? :spark, T::Array.of(T::Hash).optional
    attribute? :task_id, T::String.optional
  end
end
