# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class BigqueryConnectionAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute? :aws, T::Hash.optional
    attribute? :azure, T::Hash.optional
    attribute? :cloud_resource, T::Hash.optional
    attribute? :cloud_spanner, T::Hash.optional
    attribute? :cloud_sql, T::Hash.optional
    attribute? :configuration, T::Hash.optional
    attribute? :connection_id, T::String.optional
    attribute? :deletion_policy, T::String.optional
    attribute? :description, T::String.optional
    attribute? :friendly_name, T::String.optional
    attribute? :kms_key_name, T::String.optional
    attribute? :location, T::String.optional
    attribute? :project, T::String.optional
    attribute? :spark, T::Hash.optional
  end
end
