# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_network_security_backend_authentication_config/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleNetworkSecurityBackendAuthenticationConfig
    include Pangea::Resources::ResourceBuilder

    define_resource :google_network_security_backend_authentication_config,
      attributes_class: Google::Types::NetworkSecurityBackendAuthenticationConfigAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:client_certificate, :description, :labels, :location, :trust_config, :well_known_roots]
  end
  module Google
    include GoogleNetworkSecurityBackendAuthenticationConfig
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
