# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_dataplex_lake_iam_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleDataplexLakeIamPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :google_dataplex_lake_iam_policy,
      attributes_class: Google::Types::DataplexLakeIamPolicyAttributes,
      outputs: { id: :id },
      map: [:lake, :policy_data],
      map_present: [:location, :project]
  end
  module Google
    include GoogleDataplexLakeIamPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
