# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_scc_management_folder_security_health_analytics_custom_module/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleSccManagementFolderSecurityHealthAnalyticsCustomModule
    include Pangea::Resources::ResourceBuilder

    define_resource :google_scc_management_folder_security_health_analytics_custom_module,
      attributes_class: Google::Types::SccManagementFolderSecurityHealthAnalyticsCustomModuleAttributes,
      outputs: { id: :id },
      map: [:folder],
      map_present: [:custom_config, :display_name, :enablement_state, :location]
  end
  module Google
    include GoogleSccManagementFolderSecurityHealthAnalyticsCustomModule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
