# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_discovery_engine_data_store/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleDiscoveryEngineDataStore
    include Pangea::Resources::ResourceBuilder

    define_resource :google_discovery_engine_data_store,
      attributes_class: Google::Types::DiscoveryEngineDataStoreAttributes,
      outputs: { id: :id },
      map: [:content_config, :data_store_id, :display_name, :industry_vertical, :location],
      map_present: [:advanced_site_search_config, :document_processing_config, :kms_key_name, :solution_types],
      map_bool: [:create_advanced_site_search, :skip_default_schema_creation]
  end
  module Google
    include GoogleDiscoveryEngineDataStore
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
