# Code generated by pangea-forge.
# InSpec profile for verifying google_blockchain_node_engine_blockchain_nodes infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GOOGLE_TOKEN and GOOGLE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/google_blockchain_node_engine_blockchain_nodes/ -t google://

control 'google_blockchain_node_engine_blockchain_nodes-exists' do
  impact 1.0
  title 'Manages a google_blockchain_node_engine_blockchain_nodes resource'
  desc 'Verify that the google_blockchain_node_engine_blockchain_nodes resource exists and has expected properties'

  describe google_blockchain_node_engine_blockchain_nodes(name: attribute('id')) do
    it { should exist }
    its('blockchain_node_id') { should_not be_nil }
    its('location') { should_not be_nil }
  end
end
