# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class AppEngineServiceSplitTrafficAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :service, T::String
    attribute :split, T::Array.of(T::Hash)
    attribute? :migrate_traffic, T::Bool.optional
  end
end
