# Code generated by pangea-forge.
# InSpec profile for verifying google_compute_network_firewall_policy_rule infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GOOGLE_TOKEN and GOOGLE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/google_compute_network_firewall_policy_rule/ -t google://

control 'google_compute_network_firewall_policy_rule-exists' do
  impact 1.0
  title 'Manages a google_compute_network_firewall_policy_rule resource'
  desc 'Verify that the google_compute_network_firewall_policy_rule resource exists and has expected properties'

  describe google_compute_network_firewall_policy_rule(name: attribute('id')) do
    it { should exist }
    its('action') { should_not be_nil }
    its('direction') { should_not be_nil }
    its('firewall_policy') { should_not be_nil }
    its('match') { should_not be_nil }
    its('priority') { should_not be_nil }
  end
end
