# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class VertexAiFeaturestoreEntitytypeAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :featurestore, T::String
    attribute? :description, T::String.optional
    attribute? :labels, T::Hash.optional
    attribute? :monitoring_config, T::Array.of(T::Hash).optional
    attribute? :name, T::String.optional
  end
end
