# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_compute_region_network_endpoint/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleComputeRegionNetworkEndpoint
    include Pangea::Resources::ResourceBuilder

    define_resource :google_compute_region_network_endpoint,
      attributes_class: Google::Types::ComputeRegionNetworkEndpointAttributes,
      outputs: { id: :id },
      map: [:port, :region_network_endpoint_group],
      map_present: [:fqdn, :ip_address]
  end
  module Google
    include GoogleComputeRegionNetworkEndpoint
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
