# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_discovery_engine_acl_config/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleDiscoveryEngineAclConfig
    include Pangea::Resources::ResourceBuilder

    define_resource :google_discovery_engine_acl_config,
      attributes_class: Google::Types::DiscoveryEngineAclConfigAttributes,
      outputs: { id: :id },
      map: [:location],
      map_present: [:idp_config, :project]
  end
  module Google
    include GoogleDiscoveryEngineAclConfig
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
