# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class IdentityPlatformTenantAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :display_name, T::String
    attribute? :allow_password_signup, T::Bool.optional
    attribute? :client, T::Hash.optional
    attribute? :deletion_policy, T::String.optional
    attribute? :disable_auth, T::Bool.optional
    attribute? :enable_email_link_signin, T::Bool.optional
    attribute? :project, T::String.optional
  end
end
