# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class DialogflowCxGenerativeSettingsAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :language_code, T::String
    attribute? :fallback_settings, T::Hash.optional
    attribute? :generative_safety_settings, T::Hash.optional
    attribute? :knowledge_connector_settings, T::Hash.optional
    attribute? :llm_model_settings, T::Hash.optional
    attribute? :parent, T::String.optional
  end
end
