# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_app_engine_domain_mapping/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleAppEngineDomainMapping
    include Pangea::Resources::ResourceBuilder

    define_resource :google_app_engine_domain_mapping,
      attributes_class: Google::Types::AppEngineDomainMappingAttributes,
      outputs: { id: :id },
      map: [:domain_name],
      map_present: [:override_strategy, :ssl_settings]
  end
  module Google
    include GoogleAppEngineDomainMapping
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
