# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_dns_response_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleDnsResponsePolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :google_dns_response_policy,
      attributes_class: Google::Types::DnsResponsePolicyAttributes,
      outputs: { id: :id },
      map: [:response_policy_name],
      map_present: [:description, :gke_clusters, :networks]
  end
  module Google
    include GoogleDnsResponsePolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
