# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class StorageBatchOperationsJobAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute? :bucket_list, T::Array.of(T::Hash).optional
    attribute? :delete_object, T::Array.of(T::Hash).optional
    attribute? :delete_protection, T::Bool.optional
    attribute? :job_id, T::String.optional
    attribute? :put_metadata, T::Array.of(T::Hash).optional
    attribute? :put_object_hold, T::Array.of(T::Hash).optional
    attribute? :rewrite_object, T::Array.of(T::Hash).optional
  end
end
