# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_apigee_security_feedback/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleApigeeSecurityFeedback
    include Pangea::Resources::ResourceBuilder

    define_resource :google_apigee_security_feedback,
      attributes_class: Google::Types::ApigeeSecurityFeedbackAttributes,
      outputs: { id: :id },
      map: [:feedback_contexts, :feedback_id, :feedback_type, :org_id],
      map_present: [:comment, :deletion_policy, :display_name, :reason]
  end
  module Google
    include GoogleApigeeSecurityFeedback
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
