# Code generated by pangea-forge.
# InSpec profile for verifying google_cloud_asset_organization_feed infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GOOGLE_TOKEN and GOOGLE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/google_cloud_asset_organization_feed/ -t google://

control 'google_cloud_asset_organization_feed-exists' do
  impact 1.0
  title 'Manages a google_cloud_asset_organization_feed resource'
  desc 'Verify that the google_cloud_asset_organization_feed resource exists and has expected properties'

  describe google_cloud_asset_organization_feed(name: attribute('id')) do
    it { should exist }
    its('billing_project') { should_not be_nil }
    its('feed_id') { should_not be_nil }
    its('feed_output_config') { should_not be_nil }
    its('org_id') { should_not be_nil }
  end
end
