# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class DialogflowCxToolAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :description, T::String
    attribute :display_name, T::String
    attribute? :data_store_spec, T::Hash.optional
    attribute? :deletion_policy, T::String.optional
    attribute? :function_spec, T::Hash.optional
    attribute? :open_api_spec, T::Hash.optional
    attribute? :parent, T::String.optional
  end
end
