# Code generated by pangea-forge.
# InSpec profile for verifying google_apigee_nat_address infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GOOGLE_TOKEN and GOOGLE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/google_apigee_nat_address/ -t google://

control 'google_apigee_nat_address-exists' do
  impact 1.0
  title 'Manages a google_apigee_nat_address resource'
  desc 'Verify that the google_apigee_nat_address resource exists and has expected properties'

  describe google_apigee_nat_address(name: attribute('id')) do
    it { should exist }
    its('instance_id') { should_not be_nil }
    its('name') { should_not be_nil }
  end
end
