# Code generated by pangea-forge.
# InSpec profile for verifying google_oracle_database_odb_network infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GOOGLE_TOKEN and GOOGLE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/google_oracle_database_odb_network/ -t google://

control 'google_oracle_database_odb_network-exists' do
  impact 1.0
  title 'Manages a google_oracle_database_odb_network resource'
  desc 'Verify that the google_oracle_database_odb_network resource exists and has expected properties'

  describe google_oracle_database_odb_network(name: attribute('id')) do
    it { should exist }
    its('location') { should_not be_nil }
    its('network') { should_not be_nil }
    its('odb_network_id') { should_not be_nil }
  end
end
