# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class ComputeRegionUrlMapAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :name, T::String
    attribute? :default_route_action, T::Array.of(T::Hash).optional
    attribute? :default_service, T::String.optional
    attribute? :default_url_redirect, T::Array.of(T::Hash).optional
    attribute? :description, T::String.optional
    attribute? :host_rule, T::Array.of(T::Hash).optional
    attribute? :path_matcher, T::Array.of(T::Hash).optional
    attribute? :test, T::Array.of(T::Hash).optional
  end
end
