# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_compute_router_nat_address/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleComputeRouterNatAddress
    include Pangea::Resources::ResourceBuilder

    define_resource :google_compute_router_nat_address,
      attributes_class: Google::Types::ComputeRouterNatAddressAttributes,
      outputs: { id: :id },
      map: [:nat_ips, :router, :router_nat],
      map_present: [:deletion_policy, :drain_nat_ips, :project, :region]
  end
  module Google
    include GoogleComputeRouterNatAddress
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
