# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_dialogflow_intent/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleDialogflowIntent
    include Pangea::Resources::ResourceBuilder

    define_resource :google_dialogflow_intent,
      attributes_class: Google::Types::DialogflowIntentAttributes,
      outputs: { id: :id },
      map: [:display_name],
      map_present: [:default_response_platforms, :events, :input_context_names]
  end
  module Google
    include GoogleDialogflowIntent
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
