# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class FolderAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :display_name, T::String
    attribute :parent, T::String
    attribute? :deletion_policy, T::String.optional
    attribute? :deletion_protection, T::Bool.optional
    attribute? :tags, T::Hash.optional
  end
end
