# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class SecretManagerRegionalSecretIamPolicyAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :policy_data, T::String
    attribute :secret_id, T::String
    attribute? :location, T::String.optional
    attribute? :project, T::String.optional
  end
end
