# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_dns_managed_zone_iam_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleDnsManagedZoneIamPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :google_dns_managed_zone_iam_policy,
      attributes_class: Google::Types::DnsManagedZoneIamPolicyAttributes,
      outputs: { id: :id },
      map: [:managed_zone, :policy_data]
  end
  module Google
    include GoogleDnsManagedZoneIamPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
