# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_oracle_database_exadb_vm_cluster/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleOracleDatabaseExadbVmCluster
    include Pangea::Resources::ResourceBuilder

    define_resource :google_oracle_database_exadb_vm_cluster,
      attributes_class: Google::Types::OracleDatabaseExadbVmClusterAttributes,
      outputs: { id: :id },
      map: [:backup_odb_subnet, :display_name, :exadb_vm_cluster_id, :location, :odb_subnet, :properties],
      map_present: [:deletion_policy, :labels, :odb_network, :project],
      map_bool: [:deletion_protection]
  end
  module Google
    include GoogleOracleDatabaseExadbVmCluster
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
