# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class WorkstationsWorkstationClusterAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :network, T::String
    attribute :subnetwork, T::String
    attribute :workstation_cluster_id, T::String
    attribute? :annotations, T::Hash.optional
    attribute? :deletion_policy, T::String.optional
    attribute? :display_name, T::String.optional
    attribute? :domain_config, T::Hash.optional
    attribute? :labels, T::Hash.optional
    attribute? :location, T::String.optional
    attribute? :private_cluster_config, T::Hash.optional
    attribute? :project, T::String.optional
    attribute? :tags, T::Hash.optional
    attribute? :workstation_authorization_url, T::String.optional
    attribute? :workstation_launch_url, T::String.optional
  end
end
