# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_container_aws_node_pool/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleContainerAwsNodePool
    include Pangea::Resources::ResourceBuilder

    define_resource :google_container_aws_node_pool,
      attributes_class: Google::Types::ContainerAwsNodePoolAttributes,
      outputs: { id: :id },
      map: [:autoscaling, :cluster, :config, :location, :max_pods_constraint, :name, :subnet_id, :version],
      map_present: [:annotations, :kubelet_config, :management, :update_settings]
  end
  module Google
    include GoogleContainerAwsNodePool
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
