# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_network_connectivity_hub_iam_member/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleNetworkConnectivityHubIamMember
    include Pangea::Resources::ResourceBuilder

    define_resource :google_network_connectivity_hub_iam_member,
      attributes_class: Google::Types::NetworkConnectivityHubIamMemberAttributes,
      outputs: { id: :id },
      map: [:hub, :member, :role],
      map_present: [:condition, :project]
  end
  module Google
    include GoogleNetworkConnectivityHubIamMember
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
