# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_discovery_engine_cmek_config/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleDiscoveryEngineCmekConfig
    include Pangea::Resources::ResourceBuilder

    define_resource :google_discovery_engine_cmek_config,
      attributes_class: Google::Types::DiscoveryEngineCmekConfigAttributes,
      outputs: { id: :id },
      map: [:cmek_config_id, :kms_key, :location],
      map_present: [:deletion_policy, :project, :single_region_keys],
      map_bool: [:set_default]
  end
  module Google
    include GoogleDiscoveryEngineCmekConfig
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
