# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_kms_key_ring/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleKmsKeyRing
    include Pangea::Resources::ResourceBuilder

    define_resource :google_kms_key_ring,
      attributes_class: Google::Types::KmsKeyRingAttributes,
      outputs: { id: :id },
      map: [:location, :name],
      map_present: [:project]
  end
  module Google
    include GoogleKmsKeyRing
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
