# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_gemini_logging_setting_binding/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleGeminiLoggingSettingBinding
    include Pangea::Resources::ResourceBuilder

    define_resource :google_gemini_logging_setting_binding,
      attributes_class: Google::Types::GeminiLoggingSettingBindingAttributes,
      outputs: { id: :id },
      map: [:logging_setting_id, :setting_binding_id, :target],
      map_present: [:deletion_policy, :labels, :location, :product, :project]
  end
  module Google
    include GoogleGeminiLoggingSettingBinding
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
