# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class ApigeeEnvironmentApiRevisionDeploymentAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :api, T::String
    attribute :environment, T::String
    attribute :org_id, T::String
    attribute :revision, (T::Coercible::Integer | T::Coercible::Float)
    attribute? :deletion_policy, T::String.optional
    attribute? :override, T::Bool.optional
    attribute? :sequenced_rollout, T::Bool.optional
    attribute? :service_account, T::String.optional
  end
end
