# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class DeveloperConnectConnectionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :connection_id, T::String
    attribute :location, T::String
    attribute? :annotations, T::Hash.optional
    attribute? :bitbucket_cloud_config, T::Array.of(T::Hash).optional
    attribute? :bitbucket_data_center_config, T::Array.of(T::Hash).optional
    attribute? :crypto_key_config, T::Array.of(T::Hash).optional
    attribute? :disabled, T::Bool.optional
    attribute? :etag, T::String.optional
    attribute? :github_config, T::Array.of(T::Hash).optional
    attribute? :github_enterprise_config, T::Array.of(T::Hash).optional
    attribute? :gitlab_config, T::Array.of(T::Hash).optional
    attribute? :gitlab_enterprise_config, T::Array.of(T::Hash).optional
    attribute? :labels, T::Hash.optional
  end
end
