# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_dataplex_glossary_term/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleDataplexGlossaryTerm
    include Pangea::Resources::ResourceBuilder

    define_resource :google_dataplex_glossary_term,
      attributes_class: Google::Types::DataplexGlossaryTermAttributes,
      outputs: { id: :id },
      map: [:location, :parent],
      map_present: [:deletion_policy, :description, :display_name, :glossary_id, :labels, :project, :term_id]
  end
  module Google
    include GoogleDataplexGlossaryTerm
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
