# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class ArtifactRegistryRepositoryIamMemberAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :member, T::String
    attribute :repository, T::String
    attribute :role, T::String
    attribute? :condition, T::Hash.optional
    attribute? :location, T::String.optional
    attribute? :project, T::String.optional
  end
end
