# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_parallelstore_instance/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleParallelstoreInstance
    include Pangea::Resources::ResourceBuilder

    define_resource :google_parallelstore_instance,
      attributes_class: Google::Types::ParallelstoreInstanceAttributes,
      outputs: { id: :id },
      map: [:capacity_gib, :instance_id, :location],
      map_present: [:deployment_type, :description, :directory_stripe_level, :file_stripe_level, :labels, :network, :reserved_ip_range]
  end
  module Google
    include GoogleParallelstoreInstance
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
