# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_folder_iam_audit_config/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleFolderIamAuditConfig
    include Pangea::Resources::ResourceBuilder

    define_resource :google_folder_iam_audit_config,
      attributes_class: Google::Types::FolderIamAuditConfigAttributes,
      outputs: { id: :id },
      map: [:audit_log_config, :folder, :service]
  end
  module Google
    include GoogleFolderIamAuditConfig
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
