# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_apigee_security_monitoring_condition/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleApigeeSecurityMonitoringCondition
    include Pangea::Resources::ResourceBuilder

    define_resource :google_apigee_security_monitoring_condition,
      attributes_class: Google::Types::ApigeeSecurityMonitoringConditionAttributes,
      outputs: { id: :id },
      map: [:condition_id, :org_id, :profile, :scope],
      map_present: [:include_all_resources]
  end
  module Google
    include GoogleApigeeSecurityMonitoringCondition
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
