# Code generated by pangea-forge.
# InSpec profile for verifying google_privileged_access_manager_entitlement infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GOOGLE_TOKEN and GOOGLE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/google_privileged_access_manager_entitlement/ -t google://

control 'google_privileged_access_manager_entitlement-exists' do
  impact 1.0
  title 'Manages a google_privileged_access_manager_entitlement resource'
  desc 'Verify that the google_privileged_access_manager_entitlement resource exists and has expected properties'

  describe google_privileged_access_manager_entitlement(name: attribute('id')) do
    it { should exist }
    its('eligible_users') { should_not be_nil }
    its('entitlement_id') { should_not be_nil }
    its('location') { should_not be_nil }
    its('max_request_duration') { should_not be_nil }
    its('parent') { should_not be_nil }
    its('privileged_access') { should_not be_nil }
    its('requester_justification_config') { should_not be_nil }
  end
end
