# Code generated by pangea-forge.
# InSpec profile for verifying google_vertex_ai_feature_online_store infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GOOGLE_TOKEN and GOOGLE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/google_vertex_ai_feature_online_store/ -t google://

control 'google_vertex_ai_feature_online_store-exists' do
  impact 1.0
  title 'Manages a google_vertex_ai_feature_online_store resource'
  desc 'Verify that the google_vertex_ai_feature_online_store resource exists and has expected properties'

  describe google_vertex_ai_feature_online_store(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
  end
end
