# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_network_security_intercept_endpoint_group_association/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleNetworkSecurityInterceptEndpointGroupAssociation
    include Pangea::Resources::ResourceBuilder

    define_resource :google_network_security_intercept_endpoint_group_association,
      attributes_class: Google::Types::NetworkSecurityInterceptEndpointGroupAssociationAttributes,
      outputs: { id: :id },
      map: [:intercept_endpoint_group, :location, :network],
      map_present: [:deletion_policy, :intercept_endpoint_group_association_id, :labels, :project]
  end
  module Google
    include GoogleNetworkSecurityInterceptEndpointGroupAssociation
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
