# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class FolderIamPolicyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :folder, T::String
    attribute :policy_data, T::String
  end
end
