# Code generated by pangea-forge.
# InSpec profile for verifying google_container_analysis_note infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GOOGLE_TOKEN and GOOGLE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/google_container_analysis_note/ -t google://

control 'google_container_analysis_note-exists' do
  impact 1.0
  title 'Manages a google_container_analysis_note resource'
  desc 'Verify that the google_container_analysis_note resource exists and has expected properties'

  describe google_container_analysis_note(name: attribute('id')) do
    it { should exist }
    its('attestation_authority') { should_not be_nil }
    its('name') { should_not be_nil }
  end
end
