# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class ProjectIamAuditConfigAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :audit_log_config, T::Array.of(T::Hash)
    attribute :project, T::String
    attribute :service, T::String
  end
end
