# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class SccManagementProjectSecurityHealthAnalyticsCustomModuleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute? :custom_config, T::Array.of(T::Hash).optional
    attribute? :display_name, T::String.optional
    attribute? :enablement_state, T::String.optional
    attribute? :location, T::String.optional
  end
end
