# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class ComputeRegionDiskAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :name, T::String
    attribute :replica_zones, T::Array.of(T::String)
    attribute? :access_mode, T::String.optional
    attribute? :async_primary_disk, T::Hash.optional
    attribute? :create_snapshot_before_destroy, T::Bool.optional
    attribute? :create_snapshot_before_destroy_prefix, T::String.optional
    attribute? :deletion_policy, T::String.optional
    attribute? :description, T::String.optional
    attribute? :disk_encryption_key, T::Hash.optional
    attribute? :guest_os_features, T::Array.of(T::Hash).optional
    attribute? :image, T::String.optional
    attribute? :labels, T::Hash.optional
    attribute? :licenses, T::Array.of(T::String).optional
    attribute? :physical_block_size_bytes, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :project, T::String.optional
    attribute? :provisioned_iops, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :provisioned_throughput, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :region, T::String.optional
    attribute? :size, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :snapshot, T::String.optional
    attribute? :source_disk, T::String.optional
    attribute? :source_image_encryption_key, T::Hash.optional
    attribute? :source_snapshot_encryption_key, T::Hash.optional
    attribute? :type, T::String.optional
  end
end
