# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class CloudIdentityGroupAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :group_key, T::Array.of(T::Hash)
    attribute :labels, T::Hash
    attribute :parent, T::String
    attribute? :description, T::String.optional
    attribute? :display_name, T::String.optional
    attribute? :initial_group_config, T::String.optional
  end
end
