# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_compute_firewall_policy_with_rules/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleComputeFirewallPolicyWithRules
    include Pangea::Resources::ResourceBuilder

    define_resource :google_compute_firewall_policy_with_rules,
      attributes_class: Google::Types::ComputeFirewallPolicyWithRulesAttributes,
      outputs: { id: :id },
      map: [:parent, :rule, :short_name],
      map_present: [:description]
  end
  module Google
    include GoogleComputeFirewallPolicyWithRules
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
