# Code generated by pangea-forge.
# InSpec profile for verifying google_composer_environment infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GOOGLE_TOKEN and GOOGLE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/google_composer_environment/ -t google://

control 'google_composer_environment-exists' do
  impact 1.0
  title 'Manages a google_composer_environment resource'
  desc 'Verify that the google_composer_environment resource exists and has expected properties'

  describe google_composer_environment(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
  end
end
