# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class ContainerAzureClusterAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :authorization, T::Array.of(T::Hash)
    attribute :azure_region, T::String
    attribute :control_plane, T::Array.of(T::Hash)
    attribute :fleet, T::Array.of(T::Hash)
    attribute :location, T::String
    attribute :name, T::String
    attribute :networking, T::Array.of(T::Hash)
    attribute :resource_group_id, T::String
    attribute? :annotations, T::Hash.optional
    attribute? :azure_services_authentication, T::Array.of(T::Hash).optional
    attribute? :client, T::String.optional
    attribute? :description, T::String.optional
  end
end
