# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_monitoring_slo/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleMonitoringSlo
    include Pangea::Resources::ResourceBuilder

    define_resource :google_monitoring_slo,
      attributes_class: Google::Types::MonitoringSloAttributes,
      outputs: { id: :id },
      map: [:goal, :service],
      map_present: [:basic_sli, :calendar_period, :display_name, :request_based_sli, :rolling_period_days, :user_labels, :windows_based_sli]
  end
  module Google
    include GoogleMonitoringSlo
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
