# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class ComputeForwardingRuleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :name, T::String
    attribute? :all_ports, T::Bool.optional
    attribute? :allow_global_access, T::Bool.optional
    attribute? :allow_psc_global_access, T::Bool.optional
    attribute? :backend_service, T::String.optional
    attribute? :description, T::String.optional
    attribute? :ip_collection, T::String.optional
    attribute? :is_mirroring_collector, T::Bool.optional
    attribute? :labels, T::Hash.optional
    attribute? :load_balancing_scheme, T::String.optional
    attribute? :no_automate_dns_zone, T::Bool.optional
    attribute? :ports, T::Array.of(T::String).optional
    attribute? :recreate_closed_psc, T::Bool.optional
    attribute? :service_directory_registrations, T::Array.of(T::Hash).optional
    attribute? :service_label, T::String.optional
    attribute? :source_ip_ranges, T::Array.of(T::String).optional
    attribute? :target, T::String.optional
  end
end
