# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_notebooks_runtime/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleNotebooksRuntime
    include Pangea::Resources::ResourceBuilder

    define_resource :google_notebooks_runtime,
      attributes_class: Google::Types::NotebooksRuntimeAttributes,
      outputs: { id: :id },
      map: [:location, :name],
      map_present: [:access_config, :labels, :software_config, :virtual_machine]
  end
  module Google
    include GoogleNotebooksRuntime
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
