# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class MemorystoreInstanceDesiredUserCreatedEndpointsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :name, T::String
    attribute :region, T::String
    attribute? :desired_user_created_endpoints, T::Array.of(T::Hash).optional
  end
end
