# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_iap_web_cloud_run_service_iam_member/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleIapWebCloudRunServiceIamMember
    include Pangea::Resources::ResourceBuilder

    define_resource :google_iap_web_cloud_run_service_iam_member,
      attributes_class: Google::Types::IapWebCloudRunServiceIamMemberAttributes,
      outputs: { id: :id },
      map: [:cloud_run_service_name, :member, :role],
      map_present: [:condition]
  end
  module Google
    include GoogleIapWebCloudRunServiceIamMember
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
