# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class DataprocMetastoreTableIamPolicyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :database_id, T::String
    attribute :policy_data, T::String
    attribute :service_id, T::String
    attribute :table, T::String
  end
end
