# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class FirebaserulesReleaseAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :name, T::String
    attribute :ruleset_name, T::String
    attribute? :deletion_policy, T::String.optional
    attribute? :project, T::String.optional
  end
end
