# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_cloud_run_v2_service/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleCloudRunV2Service
    include Pangea::Resources::ResourceBuilder

    define_resource :google_cloud_run_v2_service,
      attributes_class: Google::Types::CloudRunV2ServiceAttributes,
      outputs: { id: :id },
      map: [:location, :name, :template],
      map_present: [:annotations, :binary_authorization, :build_config, :client, :client_version, :custom_audiences, :deletion_policy, :description, :ingress, :labels, :launch_stage, :multi_region_settings, :project, :scaling, :traffic],
      map_bool: [:default_uri_disabled, :deletion_protection, :iap_enabled, :invoker_iam_disabled]
  end
  module Google
    include GoogleCloudRunV2Service
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
