# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class BillingSubaccountAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :display_name, T::String
    attribute :master_billing_account, T::String
    attribute? :deletion_policy, T::String.optional
  end
end
