# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class OracleDatabaseCloudExadataInfrastructureAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :cloud_exadata_infrastructure_id, T::String
    attribute :location, T::String
    attribute? :deletion_protection, T::Bool.optional
    attribute? :display_name, T::String.optional
    attribute? :labels, T::Hash.optional
    attribute? :properties, T::Array.of(T::Hash).optional
  end
end
