# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_backup_dr_backup_vault/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleBackupDrBackupVault
    include Pangea::Resources::ResourceBuilder

    define_resource :google_backup_dr_backup_vault,
      attributes_class: Google::Types::BackupDrBackupVaultAttributes,
      outputs: { id: :id },
      map: [:backup_minimum_enforced_retention_duration, :backup_vault_id, :location],
      map_present: [:access_restriction, :annotations, :backup_retention_inheritance, :description, :effective_time, :labels],
      map_bool: [:allow_missing, :force_delete, :force_update, :ignore_backup_plan_references, :ignore_inactive_datasources]
  end
  module Google
    include GoogleBackupDrBackupVault
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
