# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_workstations_workstation_iam_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleWorkstationsWorkstationIamPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :google_workstations_workstation_iam_policy,
      attributes_class: Google::Types::WorkstationsWorkstationIamPolicyAttributes,
      outputs: { id: :id },
      map: [:policy_data, :workstation_cluster_id, :workstation_config_id, :workstation_id],
      map_present: [:location, :project]
  end
  module Google
    include GoogleWorkstationsWorkstationIamPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
