# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class DataplexLakeIamBindingAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :lake, T::String
    attribute :members, T::Array.of(T::String)
    attribute :role, T::String
    attribute? :condition, T::Array.of(T::Hash).optional
  end
end
