# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class ApigeeOrganizationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :project_id, T::String
    attribute? :analytics_region, T::String.optional
    attribute? :api_consumer_data_encryption_key_name, T::String.optional
    attribute? :api_consumer_data_location, T::String.optional
    attribute? :authorized_network, T::String.optional
    attribute? :control_plane_encryption_key_name, T::String.optional
    attribute? :description, T::String.optional
    attribute? :disable_vpc_peering, T::Bool.optional
    attribute? :display_name, T::String.optional
    attribute? :properties, T::Array.of(T::Hash).optional
    attribute? :retention, T::String.optional
    attribute? :runtime_database_encryption_key_name, T::String.optional
    attribute? :runtime_type, T::String.optional
  end
end
