# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class BeyondcorpAppConnectorAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :name, T::String
    attribute :principal_info, T::Hash
    attribute? :deletion_policy, T::String.optional
    attribute? :display_name, T::String.optional
    attribute? :labels, T::Hash.optional
    attribute? :project, T::String.optional
    attribute? :region, T::String.optional
  end
end
