# Code generated by pangea-forge.
# InSpec profile for verifying google_colab_notebook_execution infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GOOGLE_TOKEN and GOOGLE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/google_colab_notebook_execution/ -t google://

control 'google_colab_notebook_execution-exists' do
  impact 1.0
  title 'Manages a google_colab_notebook_execution resource'
  desc 'Verify that the google_colab_notebook_execution resource exists and has expected properties'

  describe google_colab_notebook_execution(name: attribute('id')) do
    it { should exist }
    its('display_name') { should_not be_nil }
    its('gcs_output_uri') { should_not be_nil }
    its('location') { should_not be_nil }
  end
end
