# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_vmwareengine_private_cloud/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleVmwareenginePrivateCloud
    include Pangea::Resources::ResourceBuilder

    define_resource :google_vmwareengine_private_cloud,
      attributes_class: Google::Types::VmwareenginePrivateCloudAttributes,
      outputs: { id: :id },
      map: [:location, :management_cluster, :name, :network_config],
      map_present: [:deletion_delay_hours, :deletion_policy, :description, :project, :type],
      map_bool: [:send_deletion_delay_hours_if_zero]
  end
  module Google
    include GoogleVmwareenginePrivateCloud
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
