# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class NetworkConnectivitySpokeAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :hub, T::String
    attribute :location, T::String
    attribute :name, T::String
    attribute? :deletion_policy, T::String.optional
    attribute? :description, T::String.optional
    attribute? :group, T::String.optional
    attribute? :labels, T::Hash.optional
    attribute? :linked_interconnect_attachments, T::Hash.optional
    attribute? :linked_producer_vpc_network, T::Hash.optional
    attribute? :linked_router_appliance_instances, T::Hash.optional
    attribute? :linked_vpc_network, T::Hash.optional
    attribute? :linked_vpn_tunnels, T::Hash.optional
    attribute? :project, T::String.optional
  end
end
