# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class ComputeNetworkFirewallPolicyAssociationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :attachment_target, T::String
    attribute :firewall_policy, T::String
    attribute :name, T::String
  end
end
