# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class ComputeRouterRoutePolicyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :name, T::String
    attribute :router, T::String
    attribute :terms, T::Array.of(T::Hash)
    attribute? :type, T::String.optional
  end
end
