# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_binary_authorization_attestor/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleBinaryAuthorizationAttestor
    include Pangea::Resources::ResourceBuilder

    define_resource :google_binary_authorization_attestor,
      attributes_class: Google::Types::BinaryAuthorizationAttestorAttributes,
      outputs: { id: :id },
      map: [:attestation_authority_note, :name],
      map_present: [:description]
  end
  module Google
    include GoogleBinaryAuthorizationAttestor
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
