# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_iap_web_backend_service_iam_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleIapWebBackendServiceIamPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :google_iap_web_backend_service_iam_policy,
      attributes_class: Google::Types::IapWebBackendServiceIamPolicyAttributes,
      outputs: { id: :id },
      map: [:policy_data, :web_backend_service]
  end
  module Google
    include GoogleIapWebBackendServiceIamPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
