# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class NetworkServicesServiceBindingAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :name, T::String
    attribute :service, T::String
    attribute? :description, T::String.optional
    attribute? :labels, T::Hash.optional
  end
end
