# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class SccNotificationConfigAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :config_id, T::String
    attribute :organization, T::String
    attribute :pubsub_topic, T::String
    attribute :streaming_config, T::Hash
    attribute? :deletion_policy, T::String.optional
    attribute? :description, T::String.optional
  end
end
