# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_compute_global_forwarding_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleComputeGlobalForwardingRule
    include Pangea::Resources::ResourceBuilder

    define_resource :google_compute_global_forwarding_rule,
      attributes_class: Google::Types::ComputeGlobalForwardingRuleAttributes,
      outputs: { id: :id },
      map: [:name, :target],
      map_present: [:description, :external_managed_backend_bucket_migration_state, :external_managed_backend_bucket_migration_testing_percentage, :ip_version, :labels, :load_balancing_scheme, :metadata_filters, :port_range, :service_directory_registrations, :source_ip_ranges],
      map_bool: [:no_automate_dns_zone]
  end
  module Google
    include GoogleComputeGlobalForwardingRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
