# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_clouddeploy_custom_target_type_iam_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleClouddeployCustomTargetTypeIamPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :google_clouddeploy_custom_target_type_iam_policy,
      attributes_class: Google::Types::ClouddeployCustomTargetTypeIamPolicyAttributes,
      outputs: { id: :id },
      map: [:name, :policy_data],
      map_present: [:location, :project]
  end
  module Google
    include GoogleClouddeployCustomTargetTypeIamPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
