# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_dataplex_aspect_type/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleDataplexAspectType
    include Pangea::Resources::ResourceBuilder

    define_resource :google_dataplex_aspect_type,
      attributes_class: Google::Types::DataplexAspectTypeAttributes,
      outputs: { id: :id },
      map_present: [:aspect_type_id, :description, :display_name, :labels, :location, :metadata_template]
  end
  module Google
    include GoogleDataplexAspectType
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
