# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_service_directory_namespace_iam_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleServiceDirectoryNamespaceIamPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :google_service_directory_namespace_iam_policy,
      attributes_class: Google::Types::ServiceDirectoryNamespaceIamPolicyAttributes,
      outputs: { id: :id },
      map: [:name, :policy_data]
  end
  module Google
    include GoogleServiceDirectoryNamespaceIamPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
