# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class AccessContextManagerServicePerimeterDryRunResourceAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :perimeter_name, T::String
    attribute :resource, T::String
    attribute? :deletion_policy, T::String.optional
  end
end
