# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_secret_manager_regional_secret_iam_binding/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleSecretManagerRegionalSecretIamBinding
    include Pangea::Resources::ResourceBuilder

    define_resource :google_secret_manager_regional_secret_iam_binding,
      attributes_class: Google::Types::SecretManagerRegionalSecretIamBindingAttributes,
      outputs: { id: :id },
      map: [:members, :role, :secret_id],
      map_present: [:condition, :location, :project]
  end
  module Google
    include GoogleSecretManagerRegionalSecretIamBinding
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
