# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class HealthcareHl7V2StoreAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :dataset, T::String
    attribute :name, T::String
    attribute? :labels, T::Hash.optional
    attribute? :notification_config, T::Array.of(T::Hash).optional
    attribute? :notification_configs, T::Array.of(T::Hash).optional
    attribute? :parser_config, T::Array.of(T::Hash).optional
    attribute? :reject_duplicate_message, T::Bool.optional
  end
end
