# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_iap_app_engine_version_iam_member/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleIapAppEngineVersionIamMember
    include Pangea::Resources::ResourceBuilder

    define_resource :google_iap_app_engine_version_iam_member,
      attributes_class: Google::Types::IapAppEngineVersionIamMemberAttributes,
      outputs: { id: :id },
      map: [:app_id, :member, :role, :service, :version_id],
      map_present: [:condition, :project]
  end
  module Google
    include GoogleIapAppEngineVersionIamMember
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
