# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class OsConfigOsPolicyAssignmentAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :instance_filter, T::Array.of(T::Hash)
    attribute :location, T::String
    attribute :name, T::String
    attribute :os_policies, T::Array.of(T::Hash)
    attribute :rollout, T::Array.of(T::Hash)
    attribute? :description, T::String.optional
    attribute? :skip_await_rollout, T::Bool.optional
  end
end
