# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class ModelArmorFloorsettingAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :filter_config, T::Array.of(T::Hash)
    attribute :location, T::String
    attribute :parent, T::String
    attribute? :ai_platform_floor_setting, T::Array.of(T::Hash).optional
    attribute? :enable_floor_setting_enforcement, T::Bool.optional
    attribute? :floor_setting_metadata, T::Array.of(T::Hash).optional
    attribute? :integrated_services, T::Array.of(T::String).optional
  end
end
