# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_bigquery_analytics_hub_data_exchange/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleBigqueryAnalyticsHubDataExchange
    include Pangea::Resources::ResourceBuilder

    define_resource :google_bigquery_analytics_hub_data_exchange,
      attributes_class: Google::Types::BigqueryAnalyticsHubDataExchangeAttributes,
      outputs: { id: :id },
      map: [:data_exchange_id, :display_name, :location],
      map_present: [:deletion_policy, :description, :discovery_type, :documentation, :icon, :primary_contact, :project, :sharing_environment_config],
      map_bool: [:log_linked_dataset_query_user_email]
  end
  module Google
    include GoogleBigqueryAnalyticsHubDataExchange
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
