# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class LoggingProjectExclusionAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :filter, T::String
    attribute :name, T::String
    attribute? :description, T::String.optional
    attribute? :disabled, T::Bool.optional
    attribute? :project, T::String.optional
  end
end
