# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class TagsTagKeyAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :parent, T::String
    attribute :short_name, T::String
    attribute? :allowed_values_regex, T::String.optional
    attribute? :deletion_policy, T::String.optional
    attribute? :description, T::String.optional
    attribute? :purpose, T::String.optional
    attribute? :purpose_data, T::Hash.optional
  end
end
