# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_oracle_database_odb_network/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleOracleDatabaseOdbNetwork
    include Pangea::Resources::ResourceBuilder

    define_resource :google_oracle_database_odb_network,
      attributes_class: Google::Types::OracleDatabaseOdbNetworkAttributes,
      outputs: { id: :id },
      map: [:location, :network, :odb_network_id],
      map_present: [:deletion_policy, :gcp_oracle_zone, :labels, :project],
      map_bool: [:deletion_protection]
  end
  module Google
    include GoogleOracleDatabaseOdbNetwork
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
