# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class VertexAiFeatureOnlineStoreAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :name, T::String
    attribute? :bigtable, T::Hash.optional
    attribute? :dedicated_serving_endpoint, T::Hash.optional
    attribute? :deletion_policy, T::String.optional
    attribute? :encryption_spec, T::Hash.optional
    attribute? :force_destroy, T::Bool.optional
    attribute? :labels, T::Hash.optional
    attribute? :optimized, T::Hash.optional
    attribute? :project, T::String.optional
    attribute? :region, T::String.optional
  end
end
