# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_network_security_mirroring_endpoint_group_association/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleNetworkSecurityMirroringEndpointGroupAssociation
    include Pangea::Resources::ResourceBuilder

    define_resource :google_network_security_mirroring_endpoint_group_association,
      attributes_class: Google::Types::NetworkSecurityMirroringEndpointGroupAssociationAttributes,
      outputs: { id: :id },
      map: [:location, :mirroring_endpoint_group, :network],
      map_present: [:labels, :mirroring_endpoint_group_association_id]
  end
  module Google
    include GoogleNetworkSecurityMirroringEndpointGroupAssociation
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
