# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class AccessContextManagerAuthorizedOrgsDescAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :name, T::String
    attribute :parent, T::String
    attribute? :asset_type, T::String.optional
    attribute? :authorization_direction, T::String.optional
    attribute? :authorization_type, T::String.optional
    attribute? :orgs, T::Array.of(T::String).optional
  end
end
