# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class ParameterManagerParameterAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :parameter_id, T::String
    attribute? :deletion_policy, T::String.optional
    attribute? :format, T::String.optional
    attribute? :kms_key, T::String.optional
    attribute? :labels, T::Hash.optional
    attribute? :project, T::String.optional
  end
end
