# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class Cloudfunctions2FunctionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :location, T::String
    attribute :name, T::String
    attribute? :build_config, T::Array.of(T::Hash).optional
    attribute? :description, T::String.optional
    attribute? :event_trigger, T::Array.of(T::Hash).optional
    attribute? :kms_key_name, T::String.optional
    attribute? :labels, T::Hash.optional
    attribute? :service_config, T::Array.of(T::Hash).optional
  end
end
