# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class ContainerAnalysisNoteAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :attestation_authority, T::Hash
    attribute :name, T::String
    attribute? :deletion_policy, T::String.optional
    attribute? :expiration_time, T::String.optional
    attribute? :long_description, T::String.optional
    attribute? :project, T::String.optional
    attribute? :related_note_names, T::Array.of(T::String).optional
    attribute? :related_url, T::Array.of(T::Hash).optional
    attribute? :short_description, T::String.optional
  end
end
