# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class MigrationCenterAssetsExportJobAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :assets_export_job_id, T::String
    attribute :location, T::String
    attribute? :condition, T::Hash.optional
    attribute? :deletion_policy, T::String.optional
    attribute? :labels, T::Hash.optional
    attribute? :performance_data, T::Hash.optional
    attribute? :project, T::String.optional
    attribute? :show_hidden, T::Bool.optional
    attribute? :signed_uri_destination, T::Hash.optional
  end
end
