# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_dataplex_asset_iam_member/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleDataplexAssetIamMember
    include Pangea::Resources::ResourceBuilder

    define_resource :google_dataplex_asset_iam_member,
      attributes_class: Google::Types::DataplexAssetIamMemberAttributes,
      outputs: { id: :id },
      map: [:asset, :dataplex_zone, :lake, :member, :role],
      map_present: [:condition, :location, :project]
  end
  module Google
    include GoogleDataplexAssetIamMember
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
