# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_compute_disk_iam_member/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleComputeDiskIamMember
    include Pangea::Resources::ResourceBuilder

    define_resource :google_compute_disk_iam_member,
      attributes_class: Google::Types::ComputeDiskIamMemberAttributes,
      outputs: { id: :id },
      map: [:member, :name, :role],
      map_present: [:condition, :project, :zone]
  end
  module Google
    include GoogleComputeDiskIamMember
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
