# Code generated by pangea-forge.
# InSpec profile for verifying google_compute_router_peer infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GOOGLE_TOKEN and GOOGLE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/google_compute_router_peer/ -t google://

control 'google_compute_router_peer-exists' do
  impact 1.0
  title 'Manages a google_compute_router_peer resource'
  desc 'Verify that the google_compute_router_peer resource exists and has expected properties'

  describe google_compute_router_peer(name: attribute('id')) do
    it { should exist }
    its('interface') { should_not be_nil }
    its('name') { should_not be_nil }
    its('peer_asn') { should_not be_nil }
    its('router') { should_not be_nil }
  end
end
