# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class AccessContextManagerAccessLevelConditionAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :access_level, T::String
    attribute? :deletion_policy, T::String.optional
    attribute? :device_policy, T::Hash.optional
    attribute? :ip_subnetworks, T::Array.of(T::String).optional
    attribute? :members, T::Array.of(T::String).optional
    attribute? :negate, T::Bool.optional
    attribute? :regions, T::Array.of(T::String).optional
    attribute? :required_access_levels, T::Array.of(T::String).optional
    attribute? :vpc_network_sources, T::Array.of(T::Hash).optional
  end
end
