# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_healthcare_hl7_v2_store_iam_member/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleHealthcareHl7V2StoreIamMember
    include Pangea::Resources::ResourceBuilder

    define_resource :google_healthcare_hl7_v2_store_iam_member,
      attributes_class: Google::Types::HealthcareHl7V2StoreIamMemberAttributes,
      outputs: { id: :id },
      map: [:hl7_v2_store_id, :member, :role],
      map_present: [:condition]
  end
  module Google
    include GoogleHealthcareHl7V2StoreIamMember
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
