# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class BigqueryAnalyticsHubListingSubscriptionAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :data_exchange_id, T::String
    attribute :destination_dataset, T::Hash
    attribute :listing_id, T::String
    attribute :location, T::String
    attribute? :deletion_policy, T::String.optional
    attribute? :project, T::String.optional
  end
end
