# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class KmsKeyRingImportJobAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Google::Types

    attribute :import_job_id, T::String
    attribute :import_method, T::String
    attribute :key_ring, T::String
    attribute :protection_level, T::String
    attribute? :deletion_policy, T::String.optional
  end
end
