# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class AlloydbInstanceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :cluster, T::String
    attribute :instance_id, T::String
    attribute :instance_type, T::String
    attribute? :annotations, T::Hash.optional
    attribute? :client_connection_config, T::Array.of(T::Hash).optional
    attribute? :display_name, T::String.optional
    attribute? :gce_zone, T::String.optional
    attribute? :labels, T::Hash.optional
    attribute? :machine_config, T::Array.of(T::Hash).optional
    attribute? :network_config, T::Array.of(T::Hash).optional
    attribute? :psc_instance_config, T::Array.of(T::Hash).optional
    attribute? :query_insights_config, T::Array.of(T::Hash).optional
    attribute? :read_pool_config, T::Array.of(T::Hash).optional
  end
end
