# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Google::Types
  include Dry.Types()

  class ComputeInstanceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Google::Types

    attribute :boot_disk, T::Array.of(T::Hash)
    attribute :machine_type, T::String
    attribute :name, T::String
    attribute :network_interface, T::Array.of(T::Hash)
    attribute? :advanced_machine_features, T::Array.of(T::Hash).optional
    attribute? :allow_stopping_for_update, T::Bool.optional
    attribute? :attached_disk, T::Array.of(T::Hash).optional
    attribute? :can_ip_forward, T::Bool.optional
    attribute? :confidential_instance_config, T::Array.of(T::Hash).optional
    attribute? :deletion_protection, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :desired_status, T::String.optional
    attribute? :enable_display, T::Bool.optional
    attribute? :guest_accelerator, T::Array.of(T::Hash).optional
    attribute? :hostname, T::String.optional
    attribute? :instance_encryption_key, T::Array.of(T::Hash).optional
    attribute? :key_revocation_action_type, T::String.optional
    attribute? :labels, T::Hash.optional
    attribute? :metadata, T::Hash.optional
    attribute? :metadata_startup_script, T::String.optional
    attribute? :network_performance_config, T::Array.of(T::Hash).optional
    attribute? :params, T::Array.of(T::Hash).optional
    attribute? :reservation_affinity, T::Array.of(T::Hash).optional
    attribute? :resource_policies, T::Array.of(T::String).optional
    attribute? :scheduling, T::Array.of(T::Hash).optional
    attribute? :scratch_disk, T::Array.of(T::Hash).optional
    attribute? :service_account, T::Array.of(T::Hash).optional
    attribute? :shielded_instance_config, T::Array.of(T::Hash).optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
