# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_ces_app_version resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleCesAppVersion do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { app: 'test-value', app_version_id: 'test-value', location: 'test-value' } }

  describe ':google_ces_app_version' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_ces_app_version('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_ces_app_version', 'test')
        validate_required_attributes(config, [:app, :app_version_id, :location])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_ces_app_version('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_ces_app_version)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_ces_app_version('test', required_attrs)

        expect(ref.id).to eq("${google_ces_app_version.test.id}")
        expect(ref.create_time).to eq("${google_ces_app_version.test.create_time}")
        expect(ref.creator).to eq("${google_ces_app_version.test.creator}")
        expect(ref.deletion_policy).to eq("${google_ces_app_version.test.deletion_policy}")
        expect(ref.etag).to eq("${google_ces_app_version.test.etag}")
        expect(ref.name).to eq("${google_ces_app_version.test.name}")
        expect(ref.project).to eq("${google_ces_app_version.test.project}")
        expect(ref.snapshot).to eq("${google_ces_app_version.test.snapshot}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_ces_app_version('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_ces_app_version', 'test')
        expect(config).not_to have_key('create_time')
        expect(config).not_to have_key('creator')
        expect(config).not_to have_key('deletion_policy')
        expect(config).not_to have_key('etag')
        expect(config).not_to have_key('name')
        expect(config).not_to have_key('project')
        expect(config).not_to have_key('snapshot')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ deletion_policy: 'test-value', description: 'test-value', display_name: 'test-value', project: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_ces_app_version('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_ces_app_version', 'full')
        expect(config).to have_key('deletion_policy')
        expect(config).to have_key('description')
        expect(config).to have_key('display_name')
        expect(config).to have_key('project')
      end
    end

    context 'optional attributes' do
      it 'includes deletion_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_ces_app_version('opt', required_attrs.merge(deletion_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_ces_app_version', 'opt')
        expect(config).to have_key('deletion_policy')
      end

      it 'omits deletion_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_ces_app_version('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_ces_app_version', 'minimal')
        expect(config).not_to have_key('deletion_policy')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_ces_app_version('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_ces_app_version', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_ces_app_version('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_ces_app_version', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes display_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_ces_app_version('opt', required_attrs.merge(display_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_ces_app_version', 'opt')
        expect(config).to have_key('display_name')
      end

      it 'omits display_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_ces_app_version('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_ces_app_version', 'minimal')
        expect(config).not_to have_key('display_name')
      end
      it 'includes project when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_ces_app_version('opt', required_attrs.merge(project: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_ces_app_version', 'opt')
        expect(config).to have_key('project')
      end

      it 'omits project when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_ces_app_version('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_ces_app_version', 'minimal')
        expect(config).not_to have_key('project')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_ces_app_version('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_ces_app_version', 'typed')
        expect(config['app']).to be_a(String)
        expect(config['app_version_id']).to be_a(String)
        expect(config['location']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_ces_app_version('first', required_attrs)
        synth.google_ces_app_version('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_ces_app_version')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_ces_app_version,
    method: :google_ces_app_version,
    required_attrs: { app: 'test-value', app_version_id: 'test-value', location: 'test-value' },
    expected_outputs: [:id, :create_time, :creator, :deletion_policy, :etag, :name, :project, :snapshot],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
