# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_apphub_workload resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleApphubWorkload do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { application_id: 'test-value', discovered_workload: 'test-value', location: 'test-value', workload_id: 'test-value' } }

  describe ':google_apphub_workload' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_apphub_workload('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_apphub_workload', 'test')
        validate_required_attributes(config, [:application_id, :discovered_workload, :location, :workload_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_apphub_workload('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_apphub_workload)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_apphub_workload('test', required_attrs)

        expect(ref.id).to eq("${google_apphub_workload.test.id}")
        expect(ref.create_time).to eq("${google_apphub_workload.test.create_time}")
        expect(ref.deletion_policy).to eq("${google_apphub_workload.test.deletion_policy}")
        expect(ref.name).to eq("${google_apphub_workload.test.name}")
        expect(ref.project).to eq("${google_apphub_workload.test.project}")
        expect(ref.state).to eq("${google_apphub_workload.test.state}")
        expect(ref.uid).to eq("${google_apphub_workload.test.uid}")
        expect(ref.update_time).to eq("${google_apphub_workload.test.update_time}")
        expect(ref.workload_properties).to eq("${google_apphub_workload.test.workload_properties}")
        expect(ref.workload_reference).to eq("${google_apphub_workload.test.workload_reference}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_apphub_workload('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_apphub_workload', 'test')
        expect(config).not_to have_key('create_time')
        expect(config).not_to have_key('deletion_policy')
        expect(config).not_to have_key('name')
        expect(config).not_to have_key('project')
        expect(config).not_to have_key('state')
        expect(config).not_to have_key('uid')
        expect(config).not_to have_key('update_time')
        expect(config).not_to have_key('workload_properties')
        expect(config).not_to have_key('workload_reference')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ attributes: { 'key1' => 'val1' }, deletion_policy: 'test-value', description: 'test-value', display_name: 'test-value', project: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_apphub_workload('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_apphub_workload', 'full')
        expect(config).to have_key('attributes')
        expect(config).to have_key('deletion_policy')
        expect(config).to have_key('description')
        expect(config).to have_key('display_name')
        expect(config).to have_key('project')
      end
    end

    context 'optional attributes' do
      it 'includes attributes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_apphub_workload('opt', required_attrs.merge(attributes: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_apphub_workload', 'opt')
        expect(config).to have_key('attributes')
      end

      it 'omits attributes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_apphub_workload('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_apphub_workload', 'minimal')
        expect(config).not_to have_key('attributes')
      end
      it 'includes deletion_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_apphub_workload('opt', required_attrs.merge(deletion_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_apphub_workload', 'opt')
        expect(config).to have_key('deletion_policy')
      end

      it 'omits deletion_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_apphub_workload('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_apphub_workload', 'minimal')
        expect(config).not_to have_key('deletion_policy')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_apphub_workload('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_apphub_workload', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_apphub_workload('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_apphub_workload', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes display_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_apphub_workload('opt', required_attrs.merge(display_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_apphub_workload', 'opt')
        expect(config).to have_key('display_name')
      end

      it 'omits display_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_apphub_workload('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_apphub_workload', 'minimal')
        expect(config).not_to have_key('display_name')
      end
      it 'includes project when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_apphub_workload('opt', required_attrs.merge(project: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_apphub_workload', 'opt')
        expect(config).to have_key('project')
      end

      it 'omits project when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_apphub_workload('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_apphub_workload', 'minimal')
        expect(config).not_to have_key('project')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_apphub_workload('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_apphub_workload', 'typed')
        expect(config['application_id']).to be_a(String)
        expect(config['discovered_workload']).to be_a(String)
        expect(config['location']).to be_a(String)
        expect(config['workload_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_apphub_workload('first', required_attrs)
        synth.google_apphub_workload('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_apphub_workload')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_apphub_workload,
    method: :google_apphub_workload,
    required_attrs: { application_id: 'test-value', discovered_workload: 'test-value', location: 'test-value', workload_id: 'test-value' },
    expected_outputs: [:id, :create_time, :deletion_policy, :name, :project, :state, :uid, :update_time, :workload_properties, :workload_reference],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
