# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_beyondcorp_security_gateway resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleBeyondcorpSecurityGateway do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { security_gateway_id: 'test-value' } }

  describe ':google_beyondcorp_security_gateway' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_beyondcorp_security_gateway', 'test')
        validate_required_attributes(config, [:security_gateway_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_beyondcorp_security_gateway('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_beyondcorp_security_gateway)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_beyondcorp_security_gateway('test', required_attrs)

        expect(ref.id).to eq("${google_beyondcorp_security_gateway.test.id}")
        expect(ref.create_time).to eq("${google_beyondcorp_security_gateway.test.create_time}")
        expect(ref.delegating_service_account).to eq("${google_beyondcorp_security_gateway.test.delegating_service_account}")
        expect(ref.deletion_policy).to eq("${google_beyondcorp_security_gateway.test.deletion_policy}")
        expect(ref.external_ips).to eq("${google_beyondcorp_security_gateway.test.external_ips}")
        expect(ref.name).to eq("${google_beyondcorp_security_gateway.test.name}")
        expect(ref.project).to eq("${google_beyondcorp_security_gateway.test.project}")
        expect(ref.state).to eq("${google_beyondcorp_security_gateway.test.state}")
        expect(ref.update_time).to eq("${google_beyondcorp_security_gateway.test.update_time}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_beyondcorp_security_gateway', 'test')
        expect(config).not_to have_key('create_time')
        expect(config).not_to have_key('delegating_service_account')
        expect(config).not_to have_key('deletion_policy')
        expect(config).not_to have_key('external_ips')
        expect(config).not_to have_key('name')
        expect(config).not_to have_key('project')
        expect(config).not_to have_key('state')
        expect(config).not_to have_key('update_time')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ deletion_policy: 'test-value', display_name: 'test-value', hubs: [{ 'key1' => 'val1' }], location: 'test-value', logging: { 'key1' => 'val1' }, project: 'test-value', proxy_protocol_config: { 'key1' => 'val1' }, service_discovery: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_beyondcorp_security_gateway', 'full')
        expect(config).to have_key('deletion_policy')
        expect(config).to have_key('display_name')
        expect(config).to have_key('hubs')
        expect(config).to have_key('location')
        expect(config).to have_key('logging')
        expect(config).to have_key('project')
        expect(config).to have_key('proxy_protocol_config')
        expect(config).to have_key('service_discovery')
      end
    end

    context 'optional attributes' do
      it 'includes deletion_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('opt', required_attrs.merge(deletion_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_beyondcorp_security_gateway', 'opt')
        expect(config).to have_key('deletion_policy')
      end

      it 'omits deletion_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_beyondcorp_security_gateway', 'minimal')
        expect(config).not_to have_key('deletion_policy')
      end
      it 'includes display_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('opt', required_attrs.merge(display_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_beyondcorp_security_gateway', 'opt')
        expect(config).to have_key('display_name')
      end

      it 'omits display_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_beyondcorp_security_gateway', 'minimal')
        expect(config).not_to have_key('display_name')
      end
      it 'includes hubs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('opt', required_attrs.merge(hubs: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_beyondcorp_security_gateway', 'opt')
        expect(config).to have_key('hubs')
      end

      it 'omits hubs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_beyondcorp_security_gateway', 'minimal')
        expect(config).not_to have_key('hubs')
      end
      it 'includes location when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('opt', required_attrs.merge(location: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_beyondcorp_security_gateway', 'opt')
        expect(config).to have_key('location')
      end

      it 'omits location when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_beyondcorp_security_gateway', 'minimal')
        expect(config).not_to have_key('location')
      end
      it 'includes logging when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('opt', required_attrs.merge(logging: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_beyondcorp_security_gateway', 'opt')
        expect(config).to have_key('logging')
      end

      it 'omits logging when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_beyondcorp_security_gateway', 'minimal')
        expect(config).not_to have_key('logging')
      end
      it 'includes project when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('opt', required_attrs.merge(project: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_beyondcorp_security_gateway', 'opt')
        expect(config).to have_key('project')
      end

      it 'omits project when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_beyondcorp_security_gateway', 'minimal')
        expect(config).not_to have_key('project')
      end
      it 'includes proxy_protocol_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('opt', required_attrs.merge(proxy_protocol_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_beyondcorp_security_gateway', 'opt')
        expect(config).to have_key('proxy_protocol_config')
      end

      it 'omits proxy_protocol_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_beyondcorp_security_gateway', 'minimal')
        expect(config).not_to have_key('proxy_protocol_config')
      end
      it 'includes service_discovery when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('opt', required_attrs.merge(service_discovery: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_beyondcorp_security_gateway', 'opt')
        expect(config).to have_key('service_discovery')
      end

      it 'omits service_discovery when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_beyondcorp_security_gateway', 'minimal')
        expect(config).not_to have_key('service_discovery')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_beyondcorp_security_gateway', 'typed')
        expect(config['security_gateway_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_beyondcorp_security_gateway('first', required_attrs)
        synth.google_beyondcorp_security_gateway('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_beyondcorp_security_gateway')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_beyondcorp_security_gateway,
    method: :google_beyondcorp_security_gateway,
    required_attrs: { security_gateway_id: 'test-value' },
    expected_outputs: [:id, :create_time, :delegating_service_account, :deletion_policy, :external_ips, :name, :project, :state, :update_time],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
