# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_logging_saved_query resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleLoggingSavedQuery do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { display_name: 'test-value', location: 'test-value', name: 'test-value', parent: 'test-value', visibility: 'test-value' } }

  describe ':google_logging_saved_query' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_logging_saved_query('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_logging_saved_query', 'test')
        validate_required_attributes(config, [:display_name, :location, :name, :parent, :visibility])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_logging_saved_query('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_logging_saved_query)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_logging_saved_query('test', required_attrs)

        expect(ref.id).to eq("${google_logging_saved_query.test.id}")
        expect(ref.create_time).to eq("${google_logging_saved_query.test.create_time}")
        expect(ref.deletion_policy).to eq("${google_logging_saved_query.test.deletion_policy}")
        expect(ref.update_time).to eq("${google_logging_saved_query.test.update_time}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_logging_saved_query('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_logging_saved_query', 'test')
        expect(config).not_to have_key('create_time')
        expect(config).not_to have_key('deletion_policy')
        expect(config).not_to have_key('update_time')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ deletion_policy: 'test-value', description: 'test-value', logging_query: { 'key1' => 'val1' }, ops_analytics_query: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_logging_saved_query('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_logging_saved_query', 'full')
        expect(config).to have_key('deletion_policy')
        expect(config).to have_key('description')
        expect(config).to have_key('logging_query')
        expect(config).to have_key('ops_analytics_query')
      end
    end

    context 'optional attributes' do
      it 'includes deletion_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_logging_saved_query('opt', required_attrs.merge(deletion_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_logging_saved_query', 'opt')
        expect(config).to have_key('deletion_policy')
      end

      it 'omits deletion_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_logging_saved_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_logging_saved_query', 'minimal')
        expect(config).not_to have_key('deletion_policy')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_logging_saved_query('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_logging_saved_query', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_logging_saved_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_logging_saved_query', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes logging_query when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_logging_saved_query('opt', required_attrs.merge(logging_query: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_logging_saved_query', 'opt')
        expect(config).to have_key('logging_query')
      end

      it 'omits logging_query when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_logging_saved_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_logging_saved_query', 'minimal')
        expect(config).not_to have_key('logging_query')
      end
      it 'includes ops_analytics_query when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_logging_saved_query('opt', required_attrs.merge(ops_analytics_query: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_logging_saved_query', 'opt')
        expect(config).to have_key('ops_analytics_query')
      end

      it 'omits ops_analytics_query when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_logging_saved_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_logging_saved_query', 'minimal')
        expect(config).not_to have_key('ops_analytics_query')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_logging_saved_query('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_logging_saved_query', 'typed')
        expect(config['display_name']).to be_a(String)
        expect(config['location']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['parent']).to be_a(String)
        expect(config['visibility']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_logging_saved_query('first', required_attrs)
        synth.google_logging_saved_query('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_logging_saved_query')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_logging_saved_query,
    method: :google_logging_saved_query,
    required_attrs: { display_name: 'test-value', location: 'test-value', name: 'test-value', parent: 'test-value', visibility: 'test-value' },
    expected_outputs: [:id, :create_time, :deletion_policy, :update_time],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
