# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_monitoring_slo resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleMonitoringSlo do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { goal: 3.14, service: 'test-value' } }

  describe ':google_monitoring_slo' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'test')
        validate_required_attributes(config, [:goal, :service])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_monitoring_slo('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_monitoring_slo)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_monitoring_slo('test', required_attrs)

        expect(ref.id).to eq("${google_monitoring_slo.test.id}")
        expect(ref.deletion_policy).to eq("${google_monitoring_slo.test.deletion_policy}")
        expect(ref.name).to eq("${google_monitoring_slo.test.name}")
        expect(ref.project).to eq("${google_monitoring_slo.test.project}")
        expect(ref.slo_id).to eq("${google_monitoring_slo.test.slo_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_monitoring_slo', 'test')
        expect(config).not_to have_key('deletion_policy')
        expect(config).not_to have_key('name')
        expect(config).not_to have_key('project')
        expect(config).not_to have_key('slo_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ basic_sli: { 'key1' => 'val1' }, calendar_period: 'test-value', deletion_policy: 'test-value', display_name: 'test-value', project: 'test-value', request_based_sli: { 'key1' => 'val1' }, rolling_period_days: 3.14, slo_id: 'test-value', user_labels: { 'key1' => 'val1' }, windows_based_sli: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_monitoring_slo', 'full')
        expect(config).to have_key('basic_sli')
        expect(config).to have_key('calendar_period')
        expect(config).to have_key('deletion_policy')
        expect(config).to have_key('display_name')
        expect(config).to have_key('project')
        expect(config).to have_key('request_based_sli')
        expect(config).to have_key('rolling_period_days')
        expect(config).to have_key('slo_id')
        expect(config).to have_key('user_labels')
        expect(config).to have_key('windows_based_sli')
      end
    end

    context 'optional attributes' do
      it 'includes basic_sli when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('opt', required_attrs.merge(basic_sli: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'opt')
        expect(config).to have_key('basic_sli')
      end

      it 'omits basic_sli when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'minimal')
        expect(config).not_to have_key('basic_sli')
      end
      it 'includes calendar_period when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('opt', required_attrs.merge(calendar_period: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'opt')
        expect(config).to have_key('calendar_period')
      end

      it 'omits calendar_period when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'minimal')
        expect(config).not_to have_key('calendar_period')
      end
      it 'includes deletion_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('opt', required_attrs.merge(deletion_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'opt')
        expect(config).to have_key('deletion_policy')
      end

      it 'omits deletion_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'minimal')
        expect(config).not_to have_key('deletion_policy')
      end
      it 'includes display_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('opt', required_attrs.merge(display_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'opt')
        expect(config).to have_key('display_name')
      end

      it 'omits display_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'minimal')
        expect(config).not_to have_key('display_name')
      end
      it 'includes project when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('opt', required_attrs.merge(project: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'opt')
        expect(config).to have_key('project')
      end

      it 'omits project when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'minimal')
        expect(config).not_to have_key('project')
      end
      it 'includes request_based_sli when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('opt', required_attrs.merge(request_based_sli: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'opt')
        expect(config).to have_key('request_based_sli')
      end

      it 'omits request_based_sli when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'minimal')
        expect(config).not_to have_key('request_based_sli')
      end
      it 'includes rolling_period_days when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('opt', required_attrs.merge(rolling_period_days: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'opt')
        expect(config).to have_key('rolling_period_days')
      end

      it 'omits rolling_period_days when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'minimal')
        expect(config).not_to have_key('rolling_period_days')
      end
      it 'includes slo_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('opt', required_attrs.merge(slo_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'opt')
        expect(config).to have_key('slo_id')
      end

      it 'omits slo_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'minimal')
        expect(config).not_to have_key('slo_id')
      end
      it 'includes user_labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('opt', required_attrs.merge(user_labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'opt')
        expect(config).to have_key('user_labels')
      end

      it 'omits user_labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'minimal')
        expect(config).not_to have_key('user_labels')
      end
      it 'includes windows_based_sli when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('opt', required_attrs.merge(windows_based_sli: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'opt')
        expect(config).to have_key('windows_based_sli')
      end

      it 'omits windows_based_sli when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_slo', 'minimal')
        expect(config).not_to have_key('windows_based_sli')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_monitoring_slo', 'typed')
        expect(config['goal']).to be_a(Float)
        expect(config['service']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_slo('first', required_attrs)
        synth.google_monitoring_slo('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_monitoring_slo')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_monitoring_slo,
    method: :google_monitoring_slo,
    required_attrs: { goal: 3.14, service: 'test-value' },
    expected_outputs: [:id, :deletion_policy, :name, :project, :slo_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
