# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_healthcare_hl7_v2_store resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleHealthcareHl7V2Store do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { dataset: 'test-value', name: 'test-value' } }

  describe ':google_healthcare_hl7_v2_store' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_healthcare_hl7_v2_store('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_healthcare_hl7_v2_store', 'test')
        validate_required_attributes(config, [:dataset, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_healthcare_hl7_v2_store('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_healthcare_hl7_v2_store)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_healthcare_hl7_v2_store('test', required_attrs)

        expect(ref.id).to eq("${google_healthcare_hl7_v2_store.test.id}")
        expect(ref.deletion_policy).to eq("${google_healthcare_hl7_v2_store.test.deletion_policy}")
        expect(ref.effective_labels).to eq("${google_healthcare_hl7_v2_store.test.effective_labels}")
        expect(ref.self_link).to eq("${google_healthcare_hl7_v2_store.test.self_link}")
        expect(ref.terraform_labels).to eq("${google_healthcare_hl7_v2_store.test.terraform_labels}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_healthcare_hl7_v2_store('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_healthcare_hl7_v2_store', 'test')
        expect(config).not_to have_key('deletion_policy')
        expect(config).not_to have_key('effective_labels')
        expect(config).not_to have_key('self_link')
        expect(config).not_to have_key('terraform_labels')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ deletion_policy: 'test-value', labels: { 'key1' => 'val1' }, notification_config: { 'key1' => 'val1' }, notification_configs: [{ 'key1' => 'val1' }], parser_config: { 'key1' => 'val1' }, reject_duplicate_message: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_healthcare_hl7_v2_store('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_healthcare_hl7_v2_store', 'full')
        expect(config).to have_key('deletion_policy')
        expect(config).to have_key('labels')
        expect(config).to have_key('notification_config')
        expect(config).to have_key('notification_configs')
        expect(config).to have_key('parser_config')
        expect(config).to have_key('reject_duplicate_message')
      end
    end

    context 'optional attributes' do
      it 'includes deletion_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_healthcare_hl7_v2_store('opt', required_attrs.merge(deletion_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_healthcare_hl7_v2_store', 'opt')
        expect(config).to have_key('deletion_policy')
      end

      it 'omits deletion_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_healthcare_hl7_v2_store('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_healthcare_hl7_v2_store', 'minimal')
        expect(config).not_to have_key('deletion_policy')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_healthcare_hl7_v2_store('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_healthcare_hl7_v2_store', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_healthcare_hl7_v2_store('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_healthcare_hl7_v2_store', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes notification_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_healthcare_hl7_v2_store('opt', required_attrs.merge(notification_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_healthcare_hl7_v2_store', 'opt')
        expect(config).to have_key('notification_config')
      end

      it 'omits notification_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_healthcare_hl7_v2_store('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_healthcare_hl7_v2_store', 'minimal')
        expect(config).not_to have_key('notification_config')
      end
      it 'includes notification_configs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_healthcare_hl7_v2_store('opt', required_attrs.merge(notification_configs: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_healthcare_hl7_v2_store', 'opt')
        expect(config).to have_key('notification_configs')
      end

      it 'omits notification_configs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_healthcare_hl7_v2_store('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_healthcare_hl7_v2_store', 'minimal')
        expect(config).not_to have_key('notification_configs')
      end
      it 'includes parser_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_healthcare_hl7_v2_store('opt', required_attrs.merge(parser_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_healthcare_hl7_v2_store', 'opt')
        expect(config).to have_key('parser_config')
      end

      it 'omits parser_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_healthcare_hl7_v2_store('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_healthcare_hl7_v2_store', 'minimal')
        expect(config).not_to have_key('parser_config')
      end
      it 'includes reject_duplicate_message when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_healthcare_hl7_v2_store('opt', required_attrs.merge(reject_duplicate_message: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_healthcare_hl7_v2_store', 'opt')
        expect(config).to have_key('reject_duplicate_message')
      end

      it 'omits reject_duplicate_message when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_healthcare_hl7_v2_store('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_healthcare_hl7_v2_store', 'minimal')
        expect(config).not_to have_key('reject_duplicate_message')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts reject_duplicate_message=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(reject_duplicate_message: val)
          synth.google_healthcare_hl7_v2_store("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'google_healthcare_hl7_v2_store', "bool_#{val}")
          expect(config['reject_duplicate_message']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_healthcare_hl7_v2_store('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_healthcare_hl7_v2_store', 'typed')
        expect(config['dataset']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_healthcare_hl7_v2_store('first', required_attrs)
        synth.google_healthcare_hl7_v2_store('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_healthcare_hl7_v2_store')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_healthcare_hl7_v2_store,
    method: :google_healthcare_hl7_v2_store,
    required_attrs: { dataset: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :deletion_policy, :effective_labels, :self_link, :terraform_labels],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:reject_duplicate_message]
end
