# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_config_deployment resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleConfigDeployment do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { location: 'test-value', name: 'test-value', service_account: 'test-value', terraform_blueprint: { 'key1' => 'val1' } } }

  describe ':google_config_deployment' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_config_deployment', 'test')
        validate_required_attributes(config, [:location, :name, :service_account, :terraform_blueprint])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_config_deployment('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_config_deployment)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_config_deployment('test', required_attrs)

        expect(ref.id).to eq("${google_config_deployment.test.id}")
        expect(ref.deletion_policy).to eq("${google_config_deployment.test.deletion_policy}")
        expect(ref.effective_annotations).to eq("${google_config_deployment.test.effective_annotations}")
        expect(ref.effective_labels).to eq("${google_config_deployment.test.effective_labels}")
        expect(ref.latest_revision).to eq("${google_config_deployment.test.latest_revision}")
        expect(ref.project).to eq("${google_config_deployment.test.project}")
        expect(ref.state).to eq("${google_config_deployment.test.state}")
        expect(ref.terraform_labels).to eq("${google_config_deployment.test.terraform_labels}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_config_deployment', 'test')
        expect(config).not_to have_key('deletion_policy')
        expect(config).not_to have_key('effective_annotations')
        expect(config).not_to have_key('effective_labels')
        expect(config).not_to have_key('latest_revision')
        expect(config).not_to have_key('project')
        expect(config).not_to have_key('state')
        expect(config).not_to have_key('terraform_labels')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ annotations: { 'key1' => 'val1' }, artifacts_gcs_bucket: 'test-value', deletion_policy: 'test-value', force_destroy: true, import_existing_resources: true, labels: { 'key1' => 'val1' }, project: 'test-value', quota_validation: 'test-value', tf_version_constraint: 'test-value', worker_pool: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_config_deployment', 'full')
        expect(config).to have_key('annotations')
        expect(config).to have_key('artifacts_gcs_bucket')
        expect(config).to have_key('deletion_policy')
        expect(config).to have_key('force_destroy')
        expect(config).to have_key('import_existing_resources')
        expect(config).to have_key('labels')
        expect(config).to have_key('project')
        expect(config).to have_key('quota_validation')
        expect(config).to have_key('tf_version_constraint')
        expect(config).to have_key('worker_pool')
      end
    end

    context 'optional attributes' do
      it 'includes annotations when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('opt', required_attrs.merge(annotations: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_config_deployment', 'opt')
        expect(config).to have_key('annotations')
      end

      it 'omits annotations when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_config_deployment', 'minimal')
        expect(config).not_to have_key('annotations')
      end
      it 'includes artifacts_gcs_bucket when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('opt', required_attrs.merge(artifacts_gcs_bucket: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_config_deployment', 'opt')
        expect(config).to have_key('artifacts_gcs_bucket')
      end

      it 'omits artifacts_gcs_bucket when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_config_deployment', 'minimal')
        expect(config).not_to have_key('artifacts_gcs_bucket')
      end
      it 'includes deletion_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('opt', required_attrs.merge(deletion_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_config_deployment', 'opt')
        expect(config).to have_key('deletion_policy')
      end

      it 'omits deletion_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_config_deployment', 'minimal')
        expect(config).not_to have_key('deletion_policy')
      end
      it 'includes force_destroy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('opt', required_attrs.merge(force_destroy: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_config_deployment', 'opt')
        expect(config).to have_key('force_destroy')
      end

      it 'omits force_destroy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_config_deployment', 'minimal')
        expect(config).not_to have_key('force_destroy')
      end
      it 'includes import_existing_resources when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('opt', required_attrs.merge(import_existing_resources: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_config_deployment', 'opt')
        expect(config).to have_key('import_existing_resources')
      end

      it 'omits import_existing_resources when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_config_deployment', 'minimal')
        expect(config).not_to have_key('import_existing_resources')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_config_deployment', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_config_deployment', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes project when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('opt', required_attrs.merge(project: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_config_deployment', 'opt')
        expect(config).to have_key('project')
      end

      it 'omits project when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_config_deployment', 'minimal')
        expect(config).not_to have_key('project')
      end
      it 'includes quota_validation when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('opt', required_attrs.merge(quota_validation: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_config_deployment', 'opt')
        expect(config).to have_key('quota_validation')
      end

      it 'omits quota_validation when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_config_deployment', 'minimal')
        expect(config).not_to have_key('quota_validation')
      end
      it 'includes tf_version_constraint when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('opt', required_attrs.merge(tf_version_constraint: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_config_deployment', 'opt')
        expect(config).to have_key('tf_version_constraint')
      end

      it 'omits tf_version_constraint when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_config_deployment', 'minimal')
        expect(config).not_to have_key('tf_version_constraint')
      end
      it 'includes worker_pool when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('opt', required_attrs.merge(worker_pool: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_config_deployment', 'opt')
        expect(config).to have_key('worker_pool')
      end

      it 'omits worker_pool when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_config_deployment', 'minimal')
        expect(config).not_to have_key('worker_pool')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts force_destroy=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(force_destroy: val)
          synth.google_config_deployment("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'google_config_deployment', "bool_#{val}")
          expect(config['force_destroy']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts import_existing_resources=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(import_existing_resources: val)
          synth.google_config_deployment("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'google_config_deployment', "bool_#{val}")
          expect(config['import_existing_resources']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_config_deployment', 'typed')
        expect(config['location']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['service_account']).to be_a(String)
        expect(config['terraform_blueprint']).to be_a(Hash)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_config_deployment('first', required_attrs)
        synth.google_config_deployment('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_config_deployment')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_config_deployment,
    method: :google_config_deployment,
    required_attrs: { location: 'test-value', name: 'test-value', service_account: 'test-value', terraform_blueprint: { 'key1' => 'val1' } },
    expected_outputs: [:id, :deletion_policy, :effective_annotations, :effective_labels, :latest_revision, :project, :state, :terraform_labels],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:force_destroy, :import_existing_resources]
end
