# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_monitoring_monitored_project resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleMonitoringMonitoredProject do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { metrics_scope: 'test-value', name: 'test-value' } }

  describe ':google_monitoring_monitored_project' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_monitored_project('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_monitoring_monitored_project', 'test')
        validate_required_attributes(config, [:metrics_scope, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_monitoring_monitored_project('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_monitoring_monitored_project)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_monitoring_monitored_project('test', required_attrs)

        expect(ref.id).to eq("${google_monitoring_monitored_project.test.id}")
        expect(ref.create_time).to eq("${google_monitoring_monitored_project.test.create_time}")
        expect(ref.deletion_policy).to eq("${google_monitoring_monitored_project.test.deletion_policy}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_monitored_project('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_monitoring_monitored_project', 'test')
        expect(config).not_to have_key('create_time')
        expect(config).not_to have_key('deletion_policy')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ deletion_policy: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_monitored_project('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_monitoring_monitored_project', 'full')
        expect(config).to have_key('deletion_policy')
      end
    end

    context 'optional attributes' do
      it 'includes deletion_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_monitored_project('opt', required_attrs.merge(deletion_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_monitored_project', 'opt')
        expect(config).to have_key('deletion_policy')
      end

      it 'omits deletion_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_monitored_project('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_monitoring_monitored_project', 'minimal')
        expect(config).not_to have_key('deletion_policy')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_monitored_project('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_monitoring_monitored_project', 'typed')
        expect(config['metrics_scope']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_monitoring_monitored_project('first', required_attrs)
        synth.google_monitoring_monitored_project('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_monitoring_monitored_project')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_monitoring_monitored_project,
    method: :google_monitoring_monitored_project,
    required_attrs: { metrics_scope: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :create_time, :deletion_policy],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
