# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_developer_connect_account_connector resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleDeveloperConnectAccountConnector do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_connector_id: 'test-value', location: 'test-value' } }

  describe ':google_developer_connect_account_connector' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_developer_connect_account_connector', 'test')
        validate_required_attributes(config, [:account_connector_id, :location])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_developer_connect_account_connector('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_developer_connect_account_connector)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_developer_connect_account_connector('test', required_attrs)

        expect(ref.id).to eq("${google_developer_connect_account_connector.test.id}")
        expect(ref.create_time).to eq("${google_developer_connect_account_connector.test.create_time}")
        expect(ref.deletion_policy).to eq("${google_developer_connect_account_connector.test.deletion_policy}")
        expect(ref.effective_annotations).to eq("${google_developer_connect_account_connector.test.effective_annotations}")
        expect(ref.effective_labels).to eq("${google_developer_connect_account_connector.test.effective_labels}")
        expect(ref.name).to eq("${google_developer_connect_account_connector.test.name}")
        expect(ref.oauth_start_uri).to eq("${google_developer_connect_account_connector.test.oauth_start_uri}")
        expect(ref.project).to eq("${google_developer_connect_account_connector.test.project}")
        expect(ref.terraform_labels).to eq("${google_developer_connect_account_connector.test.terraform_labels}")
        expect(ref.update_time).to eq("${google_developer_connect_account_connector.test.update_time}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_developer_connect_account_connector', 'test')
        expect(config).not_to have_key('create_time')
        expect(config).not_to have_key('deletion_policy')
        expect(config).not_to have_key('effective_annotations')
        expect(config).not_to have_key('effective_labels')
        expect(config).not_to have_key('name')
        expect(config).not_to have_key('oauth_start_uri')
        expect(config).not_to have_key('project')
        expect(config).not_to have_key('terraform_labels')
        expect(config).not_to have_key('update_time')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ annotations: { 'key1' => 'val1' }, custom_oauth_config: { 'key1' => 'val1' }, deletion_policy: 'test-value', etag: 'test-value', labels: { 'key1' => 'val1' }, project: 'test-value', provider_oauth_config: { 'key1' => 'val1' }, proxy_config: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_developer_connect_account_connector', 'full')
        expect(config).to have_key('annotations')
        expect(config).to have_key('custom_oauth_config')
        expect(config).to have_key('deletion_policy')
        expect(config).to have_key('etag')
        expect(config).to have_key('labels')
        expect(config).to have_key('project')
        expect(config).to have_key('provider_oauth_config')
        expect(config).to have_key('proxy_config')
      end
    end

    context 'optional attributes' do
      it 'includes annotations when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('opt', required_attrs.merge(annotations: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_developer_connect_account_connector', 'opt')
        expect(config).to have_key('annotations')
      end

      it 'omits annotations when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_developer_connect_account_connector', 'minimal')
        expect(config).not_to have_key('annotations')
      end
      it 'includes custom_oauth_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('opt', required_attrs.merge(custom_oauth_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_developer_connect_account_connector', 'opt')
        expect(config).to have_key('custom_oauth_config')
      end

      it 'omits custom_oauth_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_developer_connect_account_connector', 'minimal')
        expect(config).not_to have_key('custom_oauth_config')
      end
      it 'includes deletion_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('opt', required_attrs.merge(deletion_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_developer_connect_account_connector', 'opt')
        expect(config).to have_key('deletion_policy')
      end

      it 'omits deletion_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_developer_connect_account_connector', 'minimal')
        expect(config).not_to have_key('deletion_policy')
      end
      it 'includes etag when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('opt', required_attrs.merge(etag: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_developer_connect_account_connector', 'opt')
        expect(config).to have_key('etag')
      end

      it 'omits etag when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_developer_connect_account_connector', 'minimal')
        expect(config).not_to have_key('etag')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_developer_connect_account_connector', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_developer_connect_account_connector', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes project when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('opt', required_attrs.merge(project: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_developer_connect_account_connector', 'opt')
        expect(config).to have_key('project')
      end

      it 'omits project when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_developer_connect_account_connector', 'minimal')
        expect(config).not_to have_key('project')
      end
      it 'includes provider_oauth_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('opt', required_attrs.merge(provider_oauth_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_developer_connect_account_connector', 'opt')
        expect(config).to have_key('provider_oauth_config')
      end

      it 'omits provider_oauth_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_developer_connect_account_connector', 'minimal')
        expect(config).not_to have_key('provider_oauth_config')
      end
      it 'includes proxy_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('opt', required_attrs.merge(proxy_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_developer_connect_account_connector', 'opt')
        expect(config).to have_key('proxy_config')
      end

      it 'omits proxy_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_developer_connect_account_connector', 'minimal')
        expect(config).not_to have_key('proxy_config')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_developer_connect_account_connector', 'typed')
        expect(config['account_connector_id']).to be_a(String)
        expect(config['location']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_developer_connect_account_connector('first', required_attrs)
        synth.google_developer_connect_account_connector('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_developer_connect_account_connector')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_developer_connect_account_connector,
    method: :google_developer_connect_account_connector,
    required_attrs: { account_connector_id: 'test-value', location: 'test-value' },
    expected_outputs: [:id, :create_time, :deletion_policy, :effective_annotations, :effective_labels, :name, :oauth_start_uri, :project, :terraform_labels, :update_time],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
