# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_compute_ssl_policy resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleComputeSslPolicy do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':google_compute_ssl_policy' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_ssl_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_compute_ssl_policy', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_compute_ssl_policy('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_compute_ssl_policy)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_compute_ssl_policy('test', required_attrs)

        expect(ref.id).to eq("${google_compute_ssl_policy.test.id}")
        expect(ref.creation_timestamp).to eq("${google_compute_ssl_policy.test.creation_timestamp}")
        expect(ref.enabled_features).to eq("${google_compute_ssl_policy.test.enabled_features}")
        expect(ref.fingerprint).to eq("${google_compute_ssl_policy.test.fingerprint}")
        expect(ref.project).to eq("${google_compute_ssl_policy.test.project}")
        expect(ref.self_link).to eq("${google_compute_ssl_policy.test.self_link}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_ssl_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_compute_ssl_policy', 'test')
        expect(config).not_to have_key('creation_timestamp')
        expect(config).not_to have_key('enabled_features')
        expect(config).not_to have_key('fingerprint')
        expect(config).not_to have_key('project')
        expect(config).not_to have_key('self_link')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ custom_features: ['test-value'], description: 'test-value', min_tls_version: 'test-value', profile: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_ssl_policy('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_compute_ssl_policy', 'full')
        expect(config).to have_key('custom_features')
        expect(config).to have_key('description')
        expect(config).to have_key('min_tls_version')
        expect(config).to have_key('profile')
      end
    end

    context 'optional attributes' do
      it 'includes custom_features when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_ssl_policy('opt', required_attrs.merge(custom_features: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_compute_ssl_policy', 'opt')
        expect(config).to have_key('custom_features')
      end

      it 'omits custom_features when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_ssl_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_compute_ssl_policy', 'minimal')
        expect(config).not_to have_key('custom_features')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_ssl_policy('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_compute_ssl_policy', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_ssl_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_compute_ssl_policy', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes min_tls_version when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_ssl_policy('opt', required_attrs.merge(min_tls_version: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_compute_ssl_policy', 'opt')
        expect(config).to have_key('min_tls_version')
      end

      it 'omits min_tls_version when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_ssl_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_compute_ssl_policy', 'minimal')
        expect(config).not_to have_key('min_tls_version')
      end
      it 'includes profile when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_ssl_policy('opt', required_attrs.merge(profile: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_compute_ssl_policy', 'opt')
        expect(config).to have_key('profile')
      end

      it 'omits profile when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_ssl_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_compute_ssl_policy', 'minimal')
        expect(config).not_to have_key('profile')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_ssl_policy('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_compute_ssl_policy', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_ssl_policy('first', required_attrs)
        synth.google_compute_ssl_policy('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_compute_ssl_policy')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_compute_ssl_policy,
    method: :google_compute_ssl_policy,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :creation_timestamp, :enabled_features, :fingerprint, :project, :self_link],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
