# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_migration_center_assets_export_job resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleMigrationCenterAssetsExportJob do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { assets_export_job_id: 'test-value', location: 'test-value' } }

  describe ':google_migration_center_assets_export_job' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_migration_center_assets_export_job('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_migration_center_assets_export_job', 'test')
        validate_required_attributes(config, [:assets_export_job_id, :location])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_migration_center_assets_export_job('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_migration_center_assets_export_job)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_migration_center_assets_export_job('test', required_attrs)

        expect(ref.id).to eq("${google_migration_center_assets_export_job.test.id}")
        expect(ref.create_time).to eq("${google_migration_center_assets_export_job.test.create_time}")
        expect(ref.deletion_policy).to eq("${google_migration_center_assets_export_job.test.deletion_policy}")
        expect(ref.effective_labels).to eq("${google_migration_center_assets_export_job.test.effective_labels}")
        expect(ref.inventory).to eq("${google_migration_center_assets_export_job.test.inventory}")
        expect(ref.name).to eq("${google_migration_center_assets_export_job.test.name}")
        expect(ref.network_dependencies).to eq("${google_migration_center_assets_export_job.test.network_dependencies}")
        expect(ref.project).to eq("${google_migration_center_assets_export_job.test.project}")
        expect(ref.recent_executions).to eq("${google_migration_center_assets_export_job.test.recent_executions}")
        expect(ref.terraform_labels).to eq("${google_migration_center_assets_export_job.test.terraform_labels}")
        expect(ref.update_time).to eq("${google_migration_center_assets_export_job.test.update_time}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_migration_center_assets_export_job('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_migration_center_assets_export_job', 'test')
        expect(config).not_to have_key('create_time')
        expect(config).not_to have_key('deletion_policy')
        expect(config).not_to have_key('effective_labels')
        expect(config).not_to have_key('inventory')
        expect(config).not_to have_key('name')
        expect(config).not_to have_key('network_dependencies')
        expect(config).not_to have_key('project')
        expect(config).not_to have_key('recent_executions')
        expect(config).not_to have_key('terraform_labels')
        expect(config).not_to have_key('update_time')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ condition: { 'key1' => 'val1' }, deletion_policy: 'test-value', labels: { 'key1' => 'val1' }, performance_data: { 'key1' => 'val1' }, project: 'test-value', show_hidden: true, signed_uri_destination: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_migration_center_assets_export_job('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_migration_center_assets_export_job', 'full')
        expect(config).to have_key('condition')
        expect(config).to have_key('deletion_policy')
        expect(config).to have_key('labels')
        expect(config).to have_key('performance_data')
        expect(config).to have_key('project')
        expect(config).to have_key('show_hidden')
        expect(config).to have_key('signed_uri_destination')
      end
    end

    context 'optional attributes' do
      it 'includes condition when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_migration_center_assets_export_job('opt', required_attrs.merge(condition: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_migration_center_assets_export_job', 'opt')
        expect(config).to have_key('condition')
      end

      it 'omits condition when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_migration_center_assets_export_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_migration_center_assets_export_job', 'minimal')
        expect(config).not_to have_key('condition')
      end
      it 'includes deletion_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_migration_center_assets_export_job('opt', required_attrs.merge(deletion_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_migration_center_assets_export_job', 'opt')
        expect(config).to have_key('deletion_policy')
      end

      it 'omits deletion_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_migration_center_assets_export_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_migration_center_assets_export_job', 'minimal')
        expect(config).not_to have_key('deletion_policy')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_migration_center_assets_export_job('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_migration_center_assets_export_job', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_migration_center_assets_export_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_migration_center_assets_export_job', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes performance_data when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_migration_center_assets_export_job('opt', required_attrs.merge(performance_data: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_migration_center_assets_export_job', 'opt')
        expect(config).to have_key('performance_data')
      end

      it 'omits performance_data when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_migration_center_assets_export_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_migration_center_assets_export_job', 'minimal')
        expect(config).not_to have_key('performance_data')
      end
      it 'includes project when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_migration_center_assets_export_job('opt', required_attrs.merge(project: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_migration_center_assets_export_job', 'opt')
        expect(config).to have_key('project')
      end

      it 'omits project when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_migration_center_assets_export_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_migration_center_assets_export_job', 'minimal')
        expect(config).not_to have_key('project')
      end
      it 'includes show_hidden when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_migration_center_assets_export_job('opt', required_attrs.merge(show_hidden: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_migration_center_assets_export_job', 'opt')
        expect(config).to have_key('show_hidden')
      end

      it 'omits show_hidden when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_migration_center_assets_export_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_migration_center_assets_export_job', 'minimal')
        expect(config).not_to have_key('show_hidden')
      end
      it 'includes signed_uri_destination when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_migration_center_assets_export_job('opt', required_attrs.merge(signed_uri_destination: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_migration_center_assets_export_job', 'opt')
        expect(config).to have_key('signed_uri_destination')
      end

      it 'omits signed_uri_destination when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_migration_center_assets_export_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_migration_center_assets_export_job', 'minimal')
        expect(config).not_to have_key('signed_uri_destination')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts show_hidden=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(show_hidden: val)
          synth.google_migration_center_assets_export_job("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'google_migration_center_assets_export_job', "bool_#{val}")
          expect(config['show_hidden']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_migration_center_assets_export_job('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_migration_center_assets_export_job', 'typed')
        expect(config['assets_export_job_id']).to be_a(String)
        expect(config['location']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_migration_center_assets_export_job('first', required_attrs)
        synth.google_migration_center_assets_export_job('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_migration_center_assets_export_job')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_migration_center_assets_export_job,
    method: :google_migration_center_assets_export_job,
    required_attrs: { assets_export_job_id: 'test-value', location: 'test-value' },
    expected_outputs: [:id, :create_time, :deletion_policy, :effective_labels, :inventory, :name, :network_dependencies, :project, :recent_executions, :terraform_labels, :update_time],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:show_hidden]
end
