# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_network_connectivity_spoke resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleNetworkConnectivitySpoke do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { hub: 'test-value', location: 'test-value', name: 'test-value' } }

  describe ':google_network_connectivity_spoke' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'test')
        validate_required_attributes(config, [:hub, :location, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_network_connectivity_spoke('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_network_connectivity_spoke)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_network_connectivity_spoke('test', required_attrs)

        expect(ref.id).to eq("${google_network_connectivity_spoke.test.id}")
        expect(ref.create_time).to eq("${google_network_connectivity_spoke.test.create_time}")
        expect(ref.deletion_policy).to eq("${google_network_connectivity_spoke.test.deletion_policy}")
        expect(ref.effective_labels).to eq("${google_network_connectivity_spoke.test.effective_labels}")
        expect(ref.group).to eq("${google_network_connectivity_spoke.test.group}")
        expect(ref.project).to eq("${google_network_connectivity_spoke.test.project}")
        expect(ref.reasons).to eq("${google_network_connectivity_spoke.test.reasons}")
        expect(ref.state).to eq("${google_network_connectivity_spoke.test.state}")
        expect(ref.terraform_labels).to eq("${google_network_connectivity_spoke.test.terraform_labels}")
        expect(ref.unique_id).to eq("${google_network_connectivity_spoke.test.unique_id}")
        expect(ref.update_time).to eq("${google_network_connectivity_spoke.test.update_time}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'test')
        expect(config).not_to have_key('create_time')
        expect(config).not_to have_key('deletion_policy')
        expect(config).not_to have_key('effective_labels')
        expect(config).not_to have_key('group')
        expect(config).not_to have_key('project')
        expect(config).not_to have_key('reasons')
        expect(config).not_to have_key('state')
        expect(config).not_to have_key('terraform_labels')
        expect(config).not_to have_key('unique_id')
        expect(config).not_to have_key('update_time')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ deletion_policy: 'test-value', description: 'test-value', group: 'test-value', labels: { 'key1' => 'val1' }, linked_interconnect_attachments: { 'key1' => 'val1' }, linked_producer_vpc_network: { 'key1' => 'val1' }, linked_router_appliance_instances: { 'key1' => 'val1' }, linked_vpc_network: { 'key1' => 'val1' }, linked_vpn_tunnels: { 'key1' => 'val1' }, project: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'full')
        expect(config).to have_key('deletion_policy')
        expect(config).to have_key('description')
        expect(config).to have_key('group')
        expect(config).to have_key('labels')
        expect(config).to have_key('linked_interconnect_attachments')
        expect(config).to have_key('linked_producer_vpc_network')
        expect(config).to have_key('linked_router_appliance_instances')
        expect(config).to have_key('linked_vpc_network')
        expect(config).to have_key('linked_vpn_tunnels')
        expect(config).to have_key('project')
      end
    end

    context 'optional attributes' do
      it 'includes deletion_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('opt', required_attrs.merge(deletion_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'opt')
        expect(config).to have_key('deletion_policy')
      end

      it 'omits deletion_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'minimal')
        expect(config).not_to have_key('deletion_policy')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes group when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('opt', required_attrs.merge(group: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'opt')
        expect(config).to have_key('group')
      end

      it 'omits group when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'minimal')
        expect(config).not_to have_key('group')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes linked_interconnect_attachments when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('opt', required_attrs.merge(linked_interconnect_attachments: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'opt')
        expect(config).to have_key('linked_interconnect_attachments')
      end

      it 'omits linked_interconnect_attachments when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'minimal')
        expect(config).not_to have_key('linked_interconnect_attachments')
      end
      it 'includes linked_producer_vpc_network when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('opt', required_attrs.merge(linked_producer_vpc_network: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'opt')
        expect(config).to have_key('linked_producer_vpc_network')
      end

      it 'omits linked_producer_vpc_network when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'minimal')
        expect(config).not_to have_key('linked_producer_vpc_network')
      end
      it 'includes linked_router_appliance_instances when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('opt', required_attrs.merge(linked_router_appliance_instances: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'opt')
        expect(config).to have_key('linked_router_appliance_instances')
      end

      it 'omits linked_router_appliance_instances when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'minimal')
        expect(config).not_to have_key('linked_router_appliance_instances')
      end
      it 'includes linked_vpc_network when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('opt', required_attrs.merge(linked_vpc_network: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'opt')
        expect(config).to have_key('linked_vpc_network')
      end

      it 'omits linked_vpc_network when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'minimal')
        expect(config).not_to have_key('linked_vpc_network')
      end
      it 'includes linked_vpn_tunnels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('opt', required_attrs.merge(linked_vpn_tunnels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'opt')
        expect(config).to have_key('linked_vpn_tunnels')
      end

      it 'omits linked_vpn_tunnels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'minimal')
        expect(config).not_to have_key('linked_vpn_tunnels')
      end
      it 'includes project when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('opt', required_attrs.merge(project: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'opt')
        expect(config).to have_key('project')
      end

      it 'omits project when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'minimal')
        expect(config).not_to have_key('project')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_network_connectivity_spoke', 'typed')
        expect(config['hub']).to be_a(String)
        expect(config['location']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_network_connectivity_spoke('first', required_attrs)
        synth.google_network_connectivity_spoke('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_network_connectivity_spoke')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_network_connectivity_spoke,
    method: :google_network_connectivity_spoke,
    required_attrs: { hub: 'test-value', location: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :create_time, :deletion_policy, :effective_labels, :group, :project, :reasons, :state, :terraform_labels, :unique_id, :update_time],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
