# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_storage_anywhere_cache resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleStorageAnywhereCache do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { bucket: 'test-value', zone: 'test-value' } }

  describe ':google_storage_anywhere_cache' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_storage_anywhere_cache('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_storage_anywhere_cache', 'test')
        validate_required_attributes(config, [:bucket, :zone])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_storage_anywhere_cache('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_storage_anywhere_cache)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_storage_anywhere_cache('test', required_attrs)

        expect(ref.id).to eq("${google_storage_anywhere_cache.test.id}")
        expect(ref.anywhere_cache_id).to eq("${google_storage_anywhere_cache.test.anywhere_cache_id}")
        expect(ref.create_time).to eq("${google_storage_anywhere_cache.test.create_time}")
        expect(ref.pending_update).to eq("${google_storage_anywhere_cache.test.pending_update}")
        expect(ref.state).to eq("${google_storage_anywhere_cache.test.state}")
        expect(ref.update_time).to eq("${google_storage_anywhere_cache.test.update_time}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_storage_anywhere_cache('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_storage_anywhere_cache', 'test')
        expect(config).not_to have_key('anywhere_cache_id')
        expect(config).not_to have_key('create_time')
        expect(config).not_to have_key('pending_update')
        expect(config).not_to have_key('state')
        expect(config).not_to have_key('update_time')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ admission_policy: 'test-value', ttl: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_storage_anywhere_cache('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_storage_anywhere_cache', 'full')
        expect(config).to have_key('admission_policy')
        expect(config).to have_key('ttl')
      end
    end

    context 'optional attributes' do
      it 'includes admission_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_storage_anywhere_cache('opt', required_attrs.merge(admission_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_storage_anywhere_cache', 'opt')
        expect(config).to have_key('admission_policy')
      end

      it 'omits admission_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_storage_anywhere_cache('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_storage_anywhere_cache', 'minimal')
        expect(config).not_to have_key('admission_policy')
      end
      it 'includes ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_storage_anywhere_cache('opt', required_attrs.merge(ttl: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_storage_anywhere_cache', 'opt')
        expect(config).to have_key('ttl')
      end

      it 'omits ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_storage_anywhere_cache('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_storage_anywhere_cache', 'minimal')
        expect(config).not_to have_key('ttl')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_storage_anywhere_cache('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_storage_anywhere_cache', 'typed')
        expect(config['bucket']).to be_a(String)
        expect(config['zone']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_storage_anywhere_cache('first', required_attrs)
        synth.google_storage_anywhere_cache('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_storage_anywhere_cache')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_storage_anywhere_cache,
    method: :google_storage_anywhere_cache,
    required_attrs: { bucket: 'test-value', zone: 'test-value' },
    expected_outputs: [:id, :anywhere_cache_id, :create_time, :pending_update, :state, :update_time],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
