# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_document_ai_warehouse_location resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleDocumentAiWarehouseLocation do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { access_control_mode: 'test-value', database_type: 'test-value', location: 'test-value', project_number: 'test-value' } }

  describe ':google_document_ai_warehouse_location' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_document_ai_warehouse_location('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_document_ai_warehouse_location', 'test')
        validate_required_attributes(config, [:access_control_mode, :database_type, :location, :project_number])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_document_ai_warehouse_location('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_document_ai_warehouse_location)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_document_ai_warehouse_location('test', required_attrs)

        expect(ref.id).to eq("${google_document_ai_warehouse_location.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ document_creator_default_role: 'test-value', kms_key: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_document_ai_warehouse_location('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_document_ai_warehouse_location', 'full')
        expect(config).to have_key('document_creator_default_role')
        expect(config).to have_key('kms_key')
      end
    end

    context 'optional attributes' do
      it 'includes document_creator_default_role when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_document_ai_warehouse_location('opt', required_attrs.merge(document_creator_default_role: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_document_ai_warehouse_location', 'opt')
        expect(config).to have_key('document_creator_default_role')
      end

      it 'omits document_creator_default_role when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_document_ai_warehouse_location('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_document_ai_warehouse_location', 'minimal')
        expect(config).not_to have_key('document_creator_default_role')
      end
      it 'includes kms_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_document_ai_warehouse_location('opt', required_attrs.merge(kms_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_document_ai_warehouse_location', 'opt')
        expect(config).to have_key('kms_key')
      end

      it 'omits kms_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_document_ai_warehouse_location('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_document_ai_warehouse_location', 'minimal')
        expect(config).not_to have_key('kms_key')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_document_ai_warehouse_location('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_document_ai_warehouse_location', 'typed')
        expect(config['access_control_mode']).to be_a(String)
        expect(config['database_type']).to be_a(String)
        expect(config['location']).to be_a(String)
        expect(config['project_number']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_document_ai_warehouse_location('first', required_attrs)
        synth.google_document_ai_warehouse_location('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_document_ai_warehouse_location')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_document_ai_warehouse_location,
    method: :google_document_ai_warehouse_location,
    required_attrs: { access_control_mode: 'test-value', database_type: 'test-value', location: 'test-value', project_number: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
