# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_bigtable_gc_policy resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleBigtableGcPolicy do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { column_family: 'test-value', instance_name: 'test-value', table: 'test-value' } }

  describe ':google_bigtable_gc_policy' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_bigtable_gc_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_bigtable_gc_policy', 'test')
        validate_required_attributes(config, [:column_family, :instance_name, :table])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_bigtable_gc_policy('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_bigtable_gc_policy)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_bigtable_gc_policy('test', required_attrs)

        expect(ref.id).to eq("${google_bigtable_gc_policy.test.id}")
        expect(ref.project).to eq("${google_bigtable_gc_policy.test.project}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_bigtable_gc_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_bigtable_gc_policy', 'test')
        expect(config).not_to have_key('project')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ deletion_policy: 'test-value', gc_rules: 'test-value', ignore_warnings: true, max_age: [{ 'key1' => 'val1' }], max_version: [{ 'key1' => 'val1' }], mode: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_bigtable_gc_policy('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_bigtable_gc_policy', 'full')
        expect(config).to have_key('deletion_policy')
        expect(config).to have_key('gc_rules')
        expect(config).to have_key('ignore_warnings')
        expect(config).to have_key('max_age')
        expect(config).to have_key('max_version')
        expect(config).to have_key('mode')
      end
    end

    context 'optional attributes' do
      it 'includes deletion_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_bigtable_gc_policy('opt', required_attrs.merge(deletion_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_bigtable_gc_policy', 'opt')
        expect(config).to have_key('deletion_policy')
      end

      it 'omits deletion_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_bigtable_gc_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_bigtable_gc_policy', 'minimal')
        expect(config).not_to have_key('deletion_policy')
      end
      it 'includes gc_rules when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_bigtable_gc_policy('opt', required_attrs.merge(gc_rules: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_bigtable_gc_policy', 'opt')
        expect(config).to have_key('gc_rules')
      end

      it 'omits gc_rules when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_bigtable_gc_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_bigtable_gc_policy', 'minimal')
        expect(config).not_to have_key('gc_rules')
      end
      it 'includes ignore_warnings when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_bigtable_gc_policy('opt', required_attrs.merge(ignore_warnings: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_bigtable_gc_policy', 'opt')
        expect(config).to have_key('ignore_warnings')
      end

      it 'omits ignore_warnings when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_bigtable_gc_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_bigtable_gc_policy', 'minimal')
        expect(config).not_to have_key('ignore_warnings')
      end
      it 'includes max_age when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_bigtable_gc_policy('opt', required_attrs.merge(max_age: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_bigtable_gc_policy', 'opt')
        expect(config).to have_key('max_age')
      end

      it 'omits max_age when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_bigtable_gc_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_bigtable_gc_policy', 'minimal')
        expect(config).not_to have_key('max_age')
      end
      it 'includes max_version when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_bigtable_gc_policy('opt', required_attrs.merge(max_version: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_bigtable_gc_policy', 'opt')
        expect(config).to have_key('max_version')
      end

      it 'omits max_version when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_bigtable_gc_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_bigtable_gc_policy', 'minimal')
        expect(config).not_to have_key('max_version')
      end
      it 'includes mode when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_bigtable_gc_policy('opt', required_attrs.merge(mode: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_bigtable_gc_policy', 'opt')
        expect(config).to have_key('mode')
      end

      it 'omits mode when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_bigtable_gc_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_bigtable_gc_policy', 'minimal')
        expect(config).not_to have_key('mode')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts ignore_warnings=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(ignore_warnings: val)
          synth.google_bigtable_gc_policy("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'google_bigtable_gc_policy', "bool_#{val}")
          expect(config['ignore_warnings']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_bigtable_gc_policy('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_bigtable_gc_policy', 'typed')
        expect(config['column_family']).to be_a(String)
        expect(config['instance_name']).to be_a(String)
        expect(config['table']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_bigtable_gc_policy('first', required_attrs)
        synth.google_bigtable_gc_policy('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_bigtable_gc_policy')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_bigtable_gc_policy,
    method: :google_bigtable_gc_policy,
    required_attrs: { column_family: 'test-value', instance_name: 'test-value', table: 'test-value' },
    expected_outputs: [:id, :project],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:ignore_warnings]
end
