# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_colab_notebook_execution resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleColabNotebookExecution do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { display_name: 'test-value', gcs_output_uri: 'test-value', location: 'test-value' } }

  describe ':google_colab_notebook_execution' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'test')
        validate_required_attributes(config, [:display_name, :gcs_output_uri, :location])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_colab_notebook_execution('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_colab_notebook_execution)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_colab_notebook_execution('test', required_attrs)

        expect(ref.id).to eq("${google_colab_notebook_execution.test.id}")
        expect(ref.deletion_policy).to eq("${google_colab_notebook_execution.test.deletion_policy}")
        expect(ref.notebook_execution_job_id).to eq("${google_colab_notebook_execution.test.notebook_execution_job_id}")
        expect(ref.project).to eq("${google_colab_notebook_execution.test.project}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'test')
        expect(config).not_to have_key('deletion_policy')
        expect(config).not_to have_key('notebook_execution_job_id')
        expect(config).not_to have_key('project')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ custom_environment_spec: { 'key1' => 'val1' }, dataform_repository_source: { 'key1' => 'val1' }, deletion_policy: 'test-value', direct_notebook_source: { 'key1' => 'val1' }, execution_timeout: 'test-value', execution_user: 'test-value', gcs_notebook_source: { 'key1' => 'val1' }, notebook_execution_job_id: 'test-value', notebook_runtime_template_resource_name: 'test-value', project: 'test-value', service_account: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'full')
        expect(config).to have_key('custom_environment_spec')
        expect(config).to have_key('dataform_repository_source')
        expect(config).to have_key('deletion_policy')
        expect(config).to have_key('direct_notebook_source')
        expect(config).to have_key('execution_timeout')
        expect(config).to have_key('execution_user')
        expect(config).to have_key('gcs_notebook_source')
        expect(config).to have_key('notebook_execution_job_id')
        expect(config).to have_key('notebook_runtime_template_resource_name')
        expect(config).to have_key('project')
        expect(config).to have_key('service_account')
      end
    end

    context 'optional attributes' do
      it 'includes custom_environment_spec when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('opt', required_attrs.merge(custom_environment_spec: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'opt')
        expect(config).to have_key('custom_environment_spec')
      end

      it 'omits custom_environment_spec when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'minimal')
        expect(config).not_to have_key('custom_environment_spec')
      end
      it 'includes dataform_repository_source when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('opt', required_attrs.merge(dataform_repository_source: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'opt')
        expect(config).to have_key('dataform_repository_source')
      end

      it 'omits dataform_repository_source when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'minimal')
        expect(config).not_to have_key('dataform_repository_source')
      end
      it 'includes deletion_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('opt', required_attrs.merge(deletion_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'opt')
        expect(config).to have_key('deletion_policy')
      end

      it 'omits deletion_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'minimal')
        expect(config).not_to have_key('deletion_policy')
      end
      it 'includes direct_notebook_source when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('opt', required_attrs.merge(direct_notebook_source: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'opt')
        expect(config).to have_key('direct_notebook_source')
      end

      it 'omits direct_notebook_source when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'minimal')
        expect(config).not_to have_key('direct_notebook_source')
      end
      it 'includes execution_timeout when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('opt', required_attrs.merge(execution_timeout: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'opt')
        expect(config).to have_key('execution_timeout')
      end

      it 'omits execution_timeout when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'minimal')
        expect(config).not_to have_key('execution_timeout')
      end
      it 'includes execution_user when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('opt', required_attrs.merge(execution_user: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'opt')
        expect(config).to have_key('execution_user')
      end

      it 'omits execution_user when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'minimal')
        expect(config).not_to have_key('execution_user')
      end
      it 'includes gcs_notebook_source when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('opt', required_attrs.merge(gcs_notebook_source: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'opt')
        expect(config).to have_key('gcs_notebook_source')
      end

      it 'omits gcs_notebook_source when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'minimal')
        expect(config).not_to have_key('gcs_notebook_source')
      end
      it 'includes notebook_execution_job_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('opt', required_attrs.merge(notebook_execution_job_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'opt')
        expect(config).to have_key('notebook_execution_job_id')
      end

      it 'omits notebook_execution_job_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'minimal')
        expect(config).not_to have_key('notebook_execution_job_id')
      end
      it 'includes notebook_runtime_template_resource_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('opt', required_attrs.merge(notebook_runtime_template_resource_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'opt')
        expect(config).to have_key('notebook_runtime_template_resource_name')
      end

      it 'omits notebook_runtime_template_resource_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'minimal')
        expect(config).not_to have_key('notebook_runtime_template_resource_name')
      end
      it 'includes project when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('opt', required_attrs.merge(project: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'opt')
        expect(config).to have_key('project')
      end

      it 'omits project when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'minimal')
        expect(config).not_to have_key('project')
      end
      it 'includes service_account when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('opt', required_attrs.merge(service_account: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'opt')
        expect(config).to have_key('service_account')
      end

      it 'omits service_account when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'minimal')
        expect(config).not_to have_key('service_account')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_colab_notebook_execution', 'typed')
        expect(config['display_name']).to be_a(String)
        expect(config['gcs_output_uri']).to be_a(String)
        expect(config['location']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_colab_notebook_execution('first', required_attrs)
        synth.google_colab_notebook_execution('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_colab_notebook_execution')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_colab_notebook_execution,
    method: :google_colab_notebook_execution,
    required_attrs: { display_name: 'test-value', gcs_output_uri: 'test-value', location: 'test-value' },
    expected_outputs: [:id, :deletion_policy, :notebook_execution_job_id, :project],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
