# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_gkeonprem_vmware_admin_cluster resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleGkeonpremVmwareAdminCluster do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { location: 'test-value', name: 'test-value', network_config: { 'key1' => 'val1' } } }

  describe ':google_gkeonprem_vmware_admin_cluster' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'test')
        validate_required_attributes(config, [:location, :name, :network_config])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_gkeonprem_vmware_admin_cluster('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_gkeonprem_vmware_admin_cluster)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_gkeonprem_vmware_admin_cluster('test', required_attrs)

        expect(ref.id).to eq("${google_gkeonprem_vmware_admin_cluster.test.id}")
        expect(ref.annotations).to eq("${google_gkeonprem_vmware_admin_cluster.test.annotations}")
        expect(ref.bootstrap_cluster_membership).to eq("${google_gkeonprem_vmware_admin_cluster.test.bootstrap_cluster_membership}")
        expect(ref.create_time).to eq("${google_gkeonprem_vmware_admin_cluster.test.create_time}")
        expect(ref.description).to eq("${google_gkeonprem_vmware_admin_cluster.test.description}")
        expect(ref.effective_annotations).to eq("${google_gkeonprem_vmware_admin_cluster.test.effective_annotations}")
        expect(ref.enable_advanced_cluster).to eq("${google_gkeonprem_vmware_admin_cluster.test.enable_advanced_cluster}")
        expect(ref.endpoint).to eq("${google_gkeonprem_vmware_admin_cluster.test.endpoint}")
        expect(ref.etag).to eq("${google_gkeonprem_vmware_admin_cluster.test.etag}")
        expect(ref.fleet).to eq("${google_gkeonprem_vmware_admin_cluster.test.fleet}")
        expect(ref.image_type).to eq("${google_gkeonprem_vmware_admin_cluster.test.image_type}")
        expect(ref.local_name).to eq("${google_gkeonprem_vmware_admin_cluster.test.local_name}")
        expect(ref.project).to eq("${google_gkeonprem_vmware_admin_cluster.test.project}")
        expect(ref.reconciling).to eq("${google_gkeonprem_vmware_admin_cluster.test.reconciling}")
        expect(ref.state).to eq("${google_gkeonprem_vmware_admin_cluster.test.state}")
        expect(ref.status).to eq("${google_gkeonprem_vmware_admin_cluster.test.status}")
        expect(ref.uid).to eq("${google_gkeonprem_vmware_admin_cluster.test.uid}")
        expect(ref.update_time).to eq("${google_gkeonprem_vmware_admin_cluster.test.update_time}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'test')
        expect(config).not_to have_key('annotations')
        expect(config).not_to have_key('bootstrap_cluster_membership')
        expect(config).not_to have_key('create_time')
        expect(config).not_to have_key('description')
        expect(config).not_to have_key('effective_annotations')
        expect(config).not_to have_key('enable_advanced_cluster')
        expect(config).not_to have_key('endpoint')
        expect(config).not_to have_key('etag')
        expect(config).not_to have_key('fleet')
        expect(config).not_to have_key('image_type')
        expect(config).not_to have_key('local_name')
        expect(config).not_to have_key('project')
        expect(config).not_to have_key('reconciling')
        expect(config).not_to have_key('state')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('uid')
        expect(config).not_to have_key('update_time')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ addon_node: { 'key1' => 'val1' }, annotations: { 'key1' => 'val1' }, anti_affinity_groups: { 'key1' => 'val1' }, authorization: { 'key1' => 'val1' }, auto_repair_config: { 'key1' => 'val1' }, bootstrap_cluster_membership: 'test-value', control_plane_node: { 'key1' => 'val1' }, description: 'test-value', enable_advanced_cluster: true, image_type: 'test-value', load_balancer: { 'key1' => 'val1' }, on_prem_version: 'test-value', platform_config: { 'key1' => 'val1' }, private_registry_config: { 'key1' => 'val1' }, project: 'test-value', proxy: { 'key1' => 'val1' }, vcenter: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'full')
        expect(config).to have_key('addon_node')
        expect(config).to have_key('annotations')
        expect(config).to have_key('anti_affinity_groups')
        expect(config).to have_key('authorization')
        expect(config).to have_key('auto_repair_config')
        expect(config).to have_key('bootstrap_cluster_membership')
        expect(config).to have_key('control_plane_node')
        expect(config).to have_key('description')
        expect(config).to have_key('enable_advanced_cluster')
        expect(config).to have_key('image_type')
        expect(config).to have_key('load_balancer')
        expect(config).to have_key('on_prem_version')
        expect(config).to have_key('platform_config')
        expect(config).to have_key('private_registry_config')
        expect(config).to have_key('project')
        expect(config).to have_key('proxy')
        expect(config).to have_key('vcenter')
      end
    end

    context 'optional attributes' do
      it 'includes addon_node when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('opt', required_attrs.merge(addon_node: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'opt')
        expect(config).to have_key('addon_node')
      end

      it 'omits addon_node when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'minimal')
        expect(config).not_to have_key('addon_node')
      end
      it 'includes annotations when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('opt', required_attrs.merge(annotations: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'opt')
        expect(config).to have_key('annotations')
      end

      it 'omits annotations when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'minimal')
        expect(config).not_to have_key('annotations')
      end
      it 'includes anti_affinity_groups when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('opt', required_attrs.merge(anti_affinity_groups: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'opt')
        expect(config).to have_key('anti_affinity_groups')
      end

      it 'omits anti_affinity_groups when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'minimal')
        expect(config).not_to have_key('anti_affinity_groups')
      end
      it 'includes authorization when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('opt', required_attrs.merge(authorization: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'opt')
        expect(config).to have_key('authorization')
      end

      it 'omits authorization when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'minimal')
        expect(config).not_to have_key('authorization')
      end
      it 'includes auto_repair_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('opt', required_attrs.merge(auto_repair_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'opt')
        expect(config).to have_key('auto_repair_config')
      end

      it 'omits auto_repair_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'minimal')
        expect(config).not_to have_key('auto_repair_config')
      end
      it 'includes bootstrap_cluster_membership when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('opt', required_attrs.merge(bootstrap_cluster_membership: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'opt')
        expect(config).to have_key('bootstrap_cluster_membership')
      end

      it 'omits bootstrap_cluster_membership when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'minimal')
        expect(config).not_to have_key('bootstrap_cluster_membership')
      end
      it 'includes control_plane_node when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('opt', required_attrs.merge(control_plane_node: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'opt')
        expect(config).to have_key('control_plane_node')
      end

      it 'omits control_plane_node when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'minimal')
        expect(config).not_to have_key('control_plane_node')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes enable_advanced_cluster when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('opt', required_attrs.merge(enable_advanced_cluster: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'opt')
        expect(config).to have_key('enable_advanced_cluster')
      end

      it 'omits enable_advanced_cluster when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'minimal')
        expect(config).not_to have_key('enable_advanced_cluster')
      end
      it 'includes image_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('opt', required_attrs.merge(image_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'opt')
        expect(config).to have_key('image_type')
      end

      it 'omits image_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'minimal')
        expect(config).not_to have_key('image_type')
      end
      it 'includes load_balancer when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('opt', required_attrs.merge(load_balancer: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'opt')
        expect(config).to have_key('load_balancer')
      end

      it 'omits load_balancer when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'minimal')
        expect(config).not_to have_key('load_balancer')
      end
      it 'includes on_prem_version when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('opt', required_attrs.merge(on_prem_version: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'opt')
        expect(config).to have_key('on_prem_version')
      end

      it 'omits on_prem_version when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'minimal')
        expect(config).not_to have_key('on_prem_version')
      end
      it 'includes platform_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('opt', required_attrs.merge(platform_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'opt')
        expect(config).to have_key('platform_config')
      end

      it 'omits platform_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'minimal')
        expect(config).not_to have_key('platform_config')
      end
      it 'includes private_registry_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('opt', required_attrs.merge(private_registry_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'opt')
        expect(config).to have_key('private_registry_config')
      end

      it 'omits private_registry_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'minimal')
        expect(config).not_to have_key('private_registry_config')
      end
      it 'includes project when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('opt', required_attrs.merge(project: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'opt')
        expect(config).to have_key('project')
      end

      it 'omits project when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'minimal')
        expect(config).not_to have_key('project')
      end
      it 'includes proxy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('opt', required_attrs.merge(proxy: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'opt')
        expect(config).to have_key('proxy')
      end

      it 'omits proxy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'minimal')
        expect(config).not_to have_key('proxy')
      end
      it 'includes vcenter when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('opt', required_attrs.merge(vcenter: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'opt')
        expect(config).to have_key('vcenter')
      end

      it 'omits vcenter when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'minimal')
        expect(config).not_to have_key('vcenter')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enable_advanced_cluster=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enable_advanced_cluster: val)
          synth.google_gkeonprem_vmware_admin_cluster("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', "bool_#{val}")
          expect(config['enable_advanced_cluster']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_gkeonprem_vmware_admin_cluster', 'typed')
        expect(config['location']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['network_config']).to be_a(Hash)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_gkeonprem_vmware_admin_cluster('first', required_attrs)
        synth.google_gkeonprem_vmware_admin_cluster('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_gkeonprem_vmware_admin_cluster')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_gkeonprem_vmware_admin_cluster,
    method: :google_gkeonprem_vmware_admin_cluster,
    required_attrs: { location: 'test-value', name: 'test-value', network_config: { 'key1' => 'val1' } },
    expected_outputs: [:id, :annotations, :bootstrap_cluster_membership, :create_time, :description, :effective_annotations, :enable_advanced_cluster, :endpoint, :etag, :fleet, :image_type, :local_name, :project, :reconciling, :state, :status, :uid, :update_time],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enable_advanced_cluster]
end
