# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_cloudbuild_worker_pool resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleCloudbuildWorkerPool do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { location: 'test-value', name: 'test-value' } }

  describe ':google_cloudbuild_worker_pool' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_cloudbuild_worker_pool('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_cloudbuild_worker_pool', 'test')
        validate_required_attributes(config, [:location, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_cloudbuild_worker_pool('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_cloudbuild_worker_pool)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_cloudbuild_worker_pool('test', required_attrs)

        expect(ref.id).to eq("${google_cloudbuild_worker_pool.test.id}")
        expect(ref.create_time).to eq("${google_cloudbuild_worker_pool.test.create_time}")
        expect(ref.delete_time).to eq("${google_cloudbuild_worker_pool.test.delete_time}")
        expect(ref.deletion_policy).to eq("${google_cloudbuild_worker_pool.test.deletion_policy}")
        expect(ref.effective_annotations).to eq("${google_cloudbuild_worker_pool.test.effective_annotations}")
        expect(ref.project).to eq("${google_cloudbuild_worker_pool.test.project}")
        expect(ref.state).to eq("${google_cloudbuild_worker_pool.test.state}")
        expect(ref.uid).to eq("${google_cloudbuild_worker_pool.test.uid}")
        expect(ref.update_time).to eq("${google_cloudbuild_worker_pool.test.update_time}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_cloudbuild_worker_pool('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_cloudbuild_worker_pool', 'test')
        expect(config).not_to have_key('create_time')
        expect(config).not_to have_key('delete_time')
        expect(config).not_to have_key('deletion_policy')
        expect(config).not_to have_key('effective_annotations')
        expect(config).not_to have_key('project')
        expect(config).not_to have_key('state')
        expect(config).not_to have_key('uid')
        expect(config).not_to have_key('update_time')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ annotations: { 'key1' => 'val1' }, deletion_policy: 'test-value', display_name: 'test-value', network_config: { 'key1' => 'val1' }, private_service_connect: { 'key1' => 'val1' }, project: 'test-value', worker_config: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_cloudbuild_worker_pool('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_cloudbuild_worker_pool', 'full')
        expect(config).to have_key('annotations')
        expect(config).to have_key('deletion_policy')
        expect(config).to have_key('display_name')
        expect(config).to have_key('network_config')
        expect(config).to have_key('private_service_connect')
        expect(config).to have_key('project')
        expect(config).to have_key('worker_config')
      end
    end

    context 'optional attributes' do
      it 'includes annotations when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_cloudbuild_worker_pool('opt', required_attrs.merge(annotations: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_cloudbuild_worker_pool', 'opt')
        expect(config).to have_key('annotations')
      end

      it 'omits annotations when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_cloudbuild_worker_pool('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_cloudbuild_worker_pool', 'minimal')
        expect(config).not_to have_key('annotations')
      end
      it 'includes deletion_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_cloudbuild_worker_pool('opt', required_attrs.merge(deletion_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_cloudbuild_worker_pool', 'opt')
        expect(config).to have_key('deletion_policy')
      end

      it 'omits deletion_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_cloudbuild_worker_pool('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_cloudbuild_worker_pool', 'minimal')
        expect(config).not_to have_key('deletion_policy')
      end
      it 'includes display_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_cloudbuild_worker_pool('opt', required_attrs.merge(display_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_cloudbuild_worker_pool', 'opt')
        expect(config).to have_key('display_name')
      end

      it 'omits display_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_cloudbuild_worker_pool('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_cloudbuild_worker_pool', 'minimal')
        expect(config).not_to have_key('display_name')
      end
      it 'includes network_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_cloudbuild_worker_pool('opt', required_attrs.merge(network_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_cloudbuild_worker_pool', 'opt')
        expect(config).to have_key('network_config')
      end

      it 'omits network_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_cloudbuild_worker_pool('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_cloudbuild_worker_pool', 'minimal')
        expect(config).not_to have_key('network_config')
      end
      it 'includes private_service_connect when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_cloudbuild_worker_pool('opt', required_attrs.merge(private_service_connect: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_cloudbuild_worker_pool', 'opt')
        expect(config).to have_key('private_service_connect')
      end

      it 'omits private_service_connect when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_cloudbuild_worker_pool('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_cloudbuild_worker_pool', 'minimal')
        expect(config).not_to have_key('private_service_connect')
      end
      it 'includes project when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_cloudbuild_worker_pool('opt', required_attrs.merge(project: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_cloudbuild_worker_pool', 'opt')
        expect(config).to have_key('project')
      end

      it 'omits project when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_cloudbuild_worker_pool('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_cloudbuild_worker_pool', 'minimal')
        expect(config).not_to have_key('project')
      end
      it 'includes worker_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_cloudbuild_worker_pool('opt', required_attrs.merge(worker_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_cloudbuild_worker_pool', 'opt')
        expect(config).to have_key('worker_config')
      end

      it 'omits worker_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_cloudbuild_worker_pool('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_cloudbuild_worker_pool', 'minimal')
        expect(config).not_to have_key('worker_config')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_cloudbuild_worker_pool('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_cloudbuild_worker_pool', 'typed')
        expect(config['location']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_cloudbuild_worker_pool('first', required_attrs)
        synth.google_cloudbuild_worker_pool('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_cloudbuild_worker_pool')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_cloudbuild_worker_pool,
    method: :google_cloudbuild_worker_pool,
    required_attrs: { location: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :create_time, :delete_time, :deletion_policy, :effective_annotations, :project, :state, :uid, :update_time],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
