# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_resource_manager_lien resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleResourceManagerLien do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { origin: 'test-value', parent: 'test-value', reason: 'test-value', restrictions: ['test-value'] } }

  describe ':google_resource_manager_lien' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_resource_manager_lien('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_resource_manager_lien', 'test')
        validate_required_attributes(config, [:origin, :parent, :reason, :restrictions])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_resource_manager_lien('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_resource_manager_lien)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_resource_manager_lien('test', required_attrs)

        expect(ref.id).to eq("${google_resource_manager_lien.test.id}")
        expect(ref.create_time).to eq("${google_resource_manager_lien.test.create_time}")
        expect(ref.deletion_policy).to eq("${google_resource_manager_lien.test.deletion_policy}")
        expect(ref.name).to eq("${google_resource_manager_lien.test.name}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_resource_manager_lien('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_resource_manager_lien', 'test')
        expect(config).not_to have_key('create_time')
        expect(config).not_to have_key('deletion_policy')
        expect(config).not_to have_key('name')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ deletion_policy: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_resource_manager_lien('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_resource_manager_lien', 'full')
        expect(config).to have_key('deletion_policy')
      end
    end

    context 'optional attributes' do
      it 'includes deletion_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_resource_manager_lien('opt', required_attrs.merge(deletion_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_resource_manager_lien', 'opt')
        expect(config).to have_key('deletion_policy')
      end

      it 'omits deletion_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_resource_manager_lien('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_resource_manager_lien', 'minimal')
        expect(config).not_to have_key('deletion_policy')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_resource_manager_lien('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_resource_manager_lien', 'typed')
        expect(config['origin']).to be_a(String)
        expect(config['parent']).to be_a(String)
        expect(config['reason']).to be_a(String)
        expect(config['restrictions']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_resource_manager_lien('first', required_attrs)
        synth.google_resource_manager_lien('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_resource_manager_lien')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_resource_manager_lien,
    method: :google_resource_manager_lien,
    required_attrs: { origin: 'test-value', parent: 'test-value', reason: 'test-value', restrictions: ['test-value'] },
    expected_outputs: [:id, :create_time, :deletion_policy, :name],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
