# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_notebooks_instance resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleNotebooksInstance do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { location: 'test-value', machine_type: 'test-value', name: 'test-value' } }

  describe ':google_notebooks_instance' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'test')
        validate_required_attributes(config, [:location, :machine_type, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_notebooks_instance('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_notebooks_instance)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_notebooks_instance('test', required_attrs)

        expect(ref.id).to eq("${google_notebooks_instance.test.id}")
        expect(ref.create_time).to eq("${google_notebooks_instance.test.create_time}")
        expect(ref.deletion_policy).to eq("${google_notebooks_instance.test.deletion_policy}")
        expect(ref.disk_encryption).to eq("${google_notebooks_instance.test.disk_encryption}")
        expect(ref.effective_labels).to eq("${google_notebooks_instance.test.effective_labels}")
        expect(ref.network).to eq("${google_notebooks_instance.test.network}")
        expect(ref.project).to eq("${google_notebooks_instance.test.project}")
        expect(ref.proxy_uri).to eq("${google_notebooks_instance.test.proxy_uri}")
        expect(ref.service_account).to eq("${google_notebooks_instance.test.service_account}")
        expect(ref.service_account_scopes).to eq("${google_notebooks_instance.test.service_account_scopes}")
        expect(ref.state).to eq("${google_notebooks_instance.test.state}")
        expect(ref.subnet).to eq("${google_notebooks_instance.test.subnet}")
        expect(ref.tags).to eq("${google_notebooks_instance.test.tags}")
        expect(ref.terraform_labels).to eq("${google_notebooks_instance.test.terraform_labels}")
        expect(ref.update_time).to eq("${google_notebooks_instance.test.update_time}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_notebooks_instance', 'test')
        expect(config).not_to have_key('create_time')
        expect(config).not_to have_key('deletion_policy')
        expect(config).not_to have_key('disk_encryption')
        expect(config).not_to have_key('effective_labels')
        expect(config).not_to have_key('network')
        expect(config).not_to have_key('project')
        expect(config).not_to have_key('proxy_uri')
        expect(config).not_to have_key('service_account')
        expect(config).not_to have_key('service_account_scopes')
        expect(config).not_to have_key('state')
        expect(config).not_to have_key('subnet')
        expect(config).not_to have_key('tags')
        expect(config).not_to have_key('terraform_labels')
        expect(config).not_to have_key('update_time')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ accelerator_config: { 'key1' => 'val1' }, boot_disk_size_gb: 3.14, boot_disk_type: 'test-value', container_image: { 'key1' => 'val1' }, create_time: 'test-value', custom_gpu_driver_path: 'test-value', data_disk_size_gb: 3.14, data_disk_type: 'test-value', deletion_policy: 'test-value', desired_state: 'test-value', disk_encryption: 'test-value', install_gpu_driver: true, instance_owners: ['test-value'], kms_key: 'test-value', labels: { 'key1' => 'val1' }, metadata: { 'key1' => 'val1' }, network: 'test-value', nic_type: 'test-value', no_proxy_access: true, no_public_ip: true, no_remove_data_disk: true, post_startup_script: 'test-value', project: 'test-value', reservation_affinity: { 'key1' => 'val1' }, service_account: 'test-value', service_account_scopes: ['test-value'], shielded_instance_config: { 'key1' => 'val1' }, subnet: 'test-value', tags: ['test-value'], update_time: 'test-value', vm_image: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_notebooks_instance', 'full')
        expect(config).to have_key('accelerator_config')
        expect(config).to have_key('boot_disk_size_gb')
        expect(config).to have_key('boot_disk_type')
        expect(config).to have_key('container_image')
        expect(config).to have_key('create_time')
        expect(config).to have_key('custom_gpu_driver_path')
        expect(config).to have_key('data_disk_size_gb')
        expect(config).to have_key('data_disk_type')
        expect(config).to have_key('deletion_policy')
        expect(config).to have_key('desired_state')
        expect(config).to have_key('disk_encryption')
        expect(config).to have_key('install_gpu_driver')
        expect(config).to have_key('instance_owners')
        expect(config).to have_key('kms_key')
        expect(config).to have_key('labels')
        expect(config).to have_key('metadata')
        expect(config).to have_key('network')
        expect(config).to have_key('nic_type')
        expect(config).to have_key('no_proxy_access')
        expect(config).to have_key('no_public_ip')
        expect(config).to have_key('no_remove_data_disk')
        expect(config).to have_key('post_startup_script')
        expect(config).to have_key('project')
        expect(config).to have_key('reservation_affinity')
        expect(config).to have_key('service_account')
        expect(config).to have_key('service_account_scopes')
        expect(config).to have_key('shielded_instance_config')
        expect(config).to have_key('subnet')
        expect(config).to have_key('tags')
        expect(config).to have_key('update_time')
        expect(config).to have_key('vm_image')
      end
    end

    context 'optional attributes' do
      it 'includes accelerator_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(accelerator_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('accelerator_config')
      end

      it 'omits accelerator_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('accelerator_config')
      end
      it 'includes boot_disk_size_gb when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(boot_disk_size_gb: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('boot_disk_size_gb')
      end

      it 'omits boot_disk_size_gb when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('boot_disk_size_gb')
      end
      it 'includes boot_disk_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(boot_disk_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('boot_disk_type')
      end

      it 'omits boot_disk_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('boot_disk_type')
      end
      it 'includes container_image when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(container_image: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('container_image')
      end

      it 'omits container_image when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('container_image')
      end
      it 'includes create_time when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(create_time: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('create_time')
      end

      it 'omits create_time when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('create_time')
      end
      it 'includes custom_gpu_driver_path when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(custom_gpu_driver_path: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('custom_gpu_driver_path')
      end

      it 'omits custom_gpu_driver_path when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('custom_gpu_driver_path')
      end
      it 'includes data_disk_size_gb when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(data_disk_size_gb: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('data_disk_size_gb')
      end

      it 'omits data_disk_size_gb when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('data_disk_size_gb')
      end
      it 'includes data_disk_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(data_disk_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('data_disk_type')
      end

      it 'omits data_disk_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('data_disk_type')
      end
      it 'includes deletion_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(deletion_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('deletion_policy')
      end

      it 'omits deletion_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('deletion_policy')
      end
      it 'includes desired_state when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(desired_state: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('desired_state')
      end

      it 'omits desired_state when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('desired_state')
      end
      it 'includes disk_encryption when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(disk_encryption: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('disk_encryption')
      end

      it 'omits disk_encryption when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('disk_encryption')
      end
      it 'includes install_gpu_driver when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(install_gpu_driver: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('install_gpu_driver')
      end

      it 'omits install_gpu_driver when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('install_gpu_driver')
      end
      it 'includes instance_owners when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(instance_owners: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('instance_owners')
      end

      it 'omits instance_owners when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('instance_owners')
      end
      it 'includes kms_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(kms_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('kms_key')
      end

      it 'omits kms_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('kms_key')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes metadata when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(metadata: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('metadata')
      end

      it 'omits metadata when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('metadata')
      end
      it 'includes network when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(network: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('network')
      end

      it 'omits network when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('network')
      end
      it 'includes nic_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(nic_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('nic_type')
      end

      it 'omits nic_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('nic_type')
      end
      it 'includes no_proxy_access when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(no_proxy_access: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('no_proxy_access')
      end

      it 'omits no_proxy_access when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('no_proxy_access')
      end
      it 'includes no_public_ip when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(no_public_ip: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('no_public_ip')
      end

      it 'omits no_public_ip when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('no_public_ip')
      end
      it 'includes no_remove_data_disk when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(no_remove_data_disk: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('no_remove_data_disk')
      end

      it 'omits no_remove_data_disk when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('no_remove_data_disk')
      end
      it 'includes post_startup_script when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(post_startup_script: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('post_startup_script')
      end

      it 'omits post_startup_script when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('post_startup_script')
      end
      it 'includes project when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(project: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('project')
      end

      it 'omits project when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('project')
      end
      it 'includes reservation_affinity when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(reservation_affinity: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('reservation_affinity')
      end

      it 'omits reservation_affinity when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('reservation_affinity')
      end
      it 'includes service_account when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(service_account: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('service_account')
      end

      it 'omits service_account when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('service_account')
      end
      it 'includes service_account_scopes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(service_account_scopes: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('service_account_scopes')
      end

      it 'omits service_account_scopes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('service_account_scopes')
      end
      it 'includes shielded_instance_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(shielded_instance_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('shielded_instance_config')
      end

      it 'omits shielded_instance_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('shielded_instance_config')
      end
      it 'includes subnet when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(subnet: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('subnet')
      end

      it 'omits subnet when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('subnet')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes update_time when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(update_time: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('update_time')
      end

      it 'omits update_time when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('update_time')
      end
      it 'includes vm_image when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('opt', required_attrs.merge(vm_image: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'opt')
        expect(config).to have_key('vm_image')
      end

      it 'omits vm_image when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_notebooks_instance', 'minimal')
        expect(config).not_to have_key('vm_image')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts install_gpu_driver=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(install_gpu_driver: val)
          synth.google_notebooks_instance("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'google_notebooks_instance', "bool_#{val}")
          expect(config['install_gpu_driver']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts no_proxy_access=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(no_proxy_access: val)
          synth.google_notebooks_instance("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'google_notebooks_instance', "bool_#{val}")
          expect(config['no_proxy_access']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts no_public_ip=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(no_public_ip: val)
          synth.google_notebooks_instance("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'google_notebooks_instance', "bool_#{val}")
          expect(config['no_public_ip']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts no_remove_data_disk=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(no_remove_data_disk: val)
          synth.google_notebooks_instance("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'google_notebooks_instance', "bool_#{val}")
          expect(config['no_remove_data_disk']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_notebooks_instance', 'typed')
        expect(config['location']).to be_a(String)
        expect(config['machine_type']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_notebooks_instance('first', required_attrs)
        synth.google_notebooks_instance('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_notebooks_instance')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_notebooks_instance,
    method: :google_notebooks_instance,
    required_attrs: { location: 'test-value', machine_type: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :create_time, :deletion_policy, :disk_encryption, :effective_labels, :network, :project, :proxy_uri, :service_account, :service_account_scopes, :state, :subnet, :tags, :terraform_labels, :update_time],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:install_gpu_driver, :no_proxy_access, :no_public_ip, :no_remove_data_disk]
end
