# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_tpu_node resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleTpuNode do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { accelerator_type: 'test-value', name: 'test-value', tensorflow_version: 'test-value' } }

  describe ':google_tpu_node' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_tpu_node('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_tpu_node', 'test')
        validate_required_attributes(config, [:accelerator_type, :name, :tensorflow_version])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_tpu_node('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_tpu_node)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_tpu_node('test', required_attrs)

        expect(ref.id).to eq("${google_tpu_node.test.id}")
        expect(ref.cidr_block).to eq("${google_tpu_node.test.cidr_block}")
        expect(ref.effective_labels).to eq("${google_tpu_node.test.effective_labels}")
        expect(ref.network).to eq("${google_tpu_node.test.network}")
        expect(ref.network_endpoints).to eq("${google_tpu_node.test.network_endpoints}")
        expect(ref.project).to eq("${google_tpu_node.test.project}")
        expect(ref.service_account).to eq("${google_tpu_node.test.service_account}")
        expect(ref.terraform_labels).to eq("${google_tpu_node.test.terraform_labels}")
        expect(ref.zone).to eq("${google_tpu_node.test.zone}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_tpu_node('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_tpu_node', 'test')
        expect(config).not_to have_key('cidr_block')
        expect(config).not_to have_key('effective_labels')
        expect(config).not_to have_key('network')
        expect(config).not_to have_key('network_endpoints')
        expect(config).not_to have_key('project')
        expect(config).not_to have_key('service_account')
        expect(config).not_to have_key('terraform_labels')
        expect(config).not_to have_key('zone')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', labels: { 'key1' => 'val1' }, scheduling_config: [{ 'key1' => 'val1' }], use_service_networking: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_tpu_node('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_tpu_node', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('labels')
        expect(config).to have_key('scheduling_config')
        expect(config).to have_key('use_service_networking')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_tpu_node('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_tpu_node', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_tpu_node('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_tpu_node', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_tpu_node('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_tpu_node', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_tpu_node('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_tpu_node', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes scheduling_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_tpu_node('opt', required_attrs.merge(scheduling_config: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_tpu_node', 'opt')
        expect(config).to have_key('scheduling_config')
      end

      it 'omits scheduling_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_tpu_node('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_tpu_node', 'minimal')
        expect(config).not_to have_key('scheduling_config')
      end
      it 'includes use_service_networking when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_tpu_node('opt', required_attrs.merge(use_service_networking: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_tpu_node', 'opt')
        expect(config).to have_key('use_service_networking')
      end

      it 'omits use_service_networking when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_tpu_node('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_tpu_node', 'minimal')
        expect(config).not_to have_key('use_service_networking')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts use_service_networking=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(use_service_networking: val)
          synth.google_tpu_node("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'google_tpu_node', "bool_#{val}")
          expect(config['use_service_networking']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_tpu_node('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_tpu_node', 'typed')
        expect(config['accelerator_type']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['tensorflow_version']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_tpu_node('first', required_attrs)
        synth.google_tpu_node('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_tpu_node')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_tpu_node,
    method: :google_tpu_node,
    required_attrs: { accelerator_type: 'test-value', name: 'test-value', tensorflow_version: 'test-value' },
    expected_outputs: [:id, :cidr_block, :effective_labels, :network, :network_endpoints, :project, :service_account, :terraform_labels, :zone],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:use_service_networking]
end
