# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_compute_router_nat_address resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleComputeRouterNatAddress do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { nat_ips: ['test-value'], router: 'test-value', router_nat: 'test-value' } }

  describe ':google_compute_router_nat_address' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_router_nat_address('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_compute_router_nat_address', 'test')
        validate_required_attributes(config, [:nat_ips, :router, :router_nat])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_compute_router_nat_address('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_compute_router_nat_address)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_compute_router_nat_address('test', required_attrs)

        expect(ref.id).to eq("${google_compute_router_nat_address.test.id}")
        expect(ref.deletion_policy).to eq("${google_compute_router_nat_address.test.deletion_policy}")
        expect(ref.project).to eq("${google_compute_router_nat_address.test.project}")
        expect(ref.region).to eq("${google_compute_router_nat_address.test.region}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_router_nat_address('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_compute_router_nat_address', 'test')
        expect(config).not_to have_key('deletion_policy')
        expect(config).not_to have_key('project')
        expect(config).not_to have_key('region')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ deletion_policy: 'test-value', drain_nat_ips: ['test-value'], project: 'test-value', region: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_router_nat_address('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_compute_router_nat_address', 'full')
        expect(config).to have_key('deletion_policy')
        expect(config).to have_key('drain_nat_ips')
        expect(config).to have_key('project')
        expect(config).to have_key('region')
      end
    end

    context 'optional attributes' do
      it 'includes deletion_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_router_nat_address('opt', required_attrs.merge(deletion_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_compute_router_nat_address', 'opt')
        expect(config).to have_key('deletion_policy')
      end

      it 'omits deletion_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_router_nat_address('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_compute_router_nat_address', 'minimal')
        expect(config).not_to have_key('deletion_policy')
      end
      it 'includes drain_nat_ips when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_router_nat_address('opt', required_attrs.merge(drain_nat_ips: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_compute_router_nat_address', 'opt')
        expect(config).to have_key('drain_nat_ips')
      end

      it 'omits drain_nat_ips when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_router_nat_address('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_compute_router_nat_address', 'minimal')
        expect(config).not_to have_key('drain_nat_ips')
      end
      it 'includes project when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_router_nat_address('opt', required_attrs.merge(project: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_compute_router_nat_address', 'opt')
        expect(config).to have_key('project')
      end

      it 'omits project when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_router_nat_address('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_compute_router_nat_address', 'minimal')
        expect(config).not_to have_key('project')
      end
      it 'includes region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_router_nat_address('opt', required_attrs.merge(region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_compute_router_nat_address', 'opt')
        expect(config).to have_key('region')
      end

      it 'omits region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_router_nat_address('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_compute_router_nat_address', 'minimal')
        expect(config).not_to have_key('region')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_router_nat_address('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_compute_router_nat_address', 'typed')
        expect(config['nat_ips']).to be_a(Array)
        expect(config['router']).to be_a(String)
        expect(config['router_nat']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_compute_router_nat_address('first', required_attrs)
        synth.google_compute_router_nat_address('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_compute_router_nat_address')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_compute_router_nat_address,
    method: :google_compute_router_nat_address,
    required_attrs: { nat_ips: ['test-value'], router: 'test-value', router_nat: 'test-value' },
    expected_outputs: [:id, :deletion_policy, :project, :region],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
