# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_parallelstore_instance resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleParallelstoreInstance do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { capacity_gib: 'test-value', instance_id: 'test-value', location: 'test-value' } }

  describe ':google_parallelstore_instance' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_parallelstore_instance', 'test')
        validate_required_attributes(config, [:capacity_gib, :instance_id, :location])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_parallelstore_instance('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_parallelstore_instance)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_parallelstore_instance('test', required_attrs)

        expect(ref.id).to eq("${google_parallelstore_instance.test.id}")
        expect(ref.access_points).to eq("${google_parallelstore_instance.test.access_points}")
        expect(ref.create_time).to eq("${google_parallelstore_instance.test.create_time}")
        expect(ref.daos_version).to eq("${google_parallelstore_instance.test.daos_version}")
        expect(ref.deletion_policy).to eq("${google_parallelstore_instance.test.deletion_policy}")
        expect(ref.effective_labels).to eq("${google_parallelstore_instance.test.effective_labels}")
        expect(ref.effective_reserved_ip_range).to eq("${google_parallelstore_instance.test.effective_reserved_ip_range}")
        expect(ref.name).to eq("${google_parallelstore_instance.test.name}")
        expect(ref.project).to eq("${google_parallelstore_instance.test.project}")
        expect(ref.state).to eq("${google_parallelstore_instance.test.state}")
        expect(ref.terraform_labels).to eq("${google_parallelstore_instance.test.terraform_labels}")
        expect(ref.update_time).to eq("${google_parallelstore_instance.test.update_time}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_parallelstore_instance', 'test')
        expect(config).not_to have_key('access_points')
        expect(config).not_to have_key('create_time')
        expect(config).not_to have_key('daos_version')
        expect(config).not_to have_key('deletion_policy')
        expect(config).not_to have_key('effective_labels')
        expect(config).not_to have_key('effective_reserved_ip_range')
        expect(config).not_to have_key('name')
        expect(config).not_to have_key('project')
        expect(config).not_to have_key('state')
        expect(config).not_to have_key('terraform_labels')
        expect(config).not_to have_key('update_time')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ deletion_policy: 'test-value', deployment_type: 'test-value', description: 'test-value', directory_stripe_level: 'test-value', file_stripe_level: 'test-value', labels: { 'key1' => 'val1' }, network: 'test-value', project: 'test-value', reserved_ip_range: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_parallelstore_instance', 'full')
        expect(config).to have_key('deletion_policy')
        expect(config).to have_key('deployment_type')
        expect(config).to have_key('description')
        expect(config).to have_key('directory_stripe_level')
        expect(config).to have_key('file_stripe_level')
        expect(config).to have_key('labels')
        expect(config).to have_key('network')
        expect(config).to have_key('project')
        expect(config).to have_key('reserved_ip_range')
      end
    end

    context 'optional attributes' do
      it 'includes deletion_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('opt', required_attrs.merge(deletion_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_parallelstore_instance', 'opt')
        expect(config).to have_key('deletion_policy')
      end

      it 'omits deletion_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_parallelstore_instance', 'minimal')
        expect(config).not_to have_key('deletion_policy')
      end
      it 'includes deployment_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('opt', required_attrs.merge(deployment_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_parallelstore_instance', 'opt')
        expect(config).to have_key('deployment_type')
      end

      it 'omits deployment_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_parallelstore_instance', 'minimal')
        expect(config).not_to have_key('deployment_type')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_parallelstore_instance', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_parallelstore_instance', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes directory_stripe_level when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('opt', required_attrs.merge(directory_stripe_level: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_parallelstore_instance', 'opt')
        expect(config).to have_key('directory_stripe_level')
      end

      it 'omits directory_stripe_level when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_parallelstore_instance', 'minimal')
        expect(config).not_to have_key('directory_stripe_level')
      end
      it 'includes file_stripe_level when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('opt', required_attrs.merge(file_stripe_level: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_parallelstore_instance', 'opt')
        expect(config).to have_key('file_stripe_level')
      end

      it 'omits file_stripe_level when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_parallelstore_instance', 'minimal')
        expect(config).not_to have_key('file_stripe_level')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_parallelstore_instance', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_parallelstore_instance', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes network when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('opt', required_attrs.merge(network: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_parallelstore_instance', 'opt')
        expect(config).to have_key('network')
      end

      it 'omits network when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_parallelstore_instance', 'minimal')
        expect(config).not_to have_key('network')
      end
      it 'includes project when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('opt', required_attrs.merge(project: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_parallelstore_instance', 'opt')
        expect(config).to have_key('project')
      end

      it 'omits project when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_parallelstore_instance', 'minimal')
        expect(config).not_to have_key('project')
      end
      it 'includes reserved_ip_range when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('opt', required_attrs.merge(reserved_ip_range: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_parallelstore_instance', 'opt')
        expect(config).to have_key('reserved_ip_range')
      end

      it 'omits reserved_ip_range when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_parallelstore_instance', 'minimal')
        expect(config).not_to have_key('reserved_ip_range')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_parallelstore_instance', 'typed')
        expect(config['capacity_gib']).to be_a(String)
        expect(config['instance_id']).to be_a(String)
        expect(config['location']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_parallelstore_instance('first', required_attrs)
        synth.google_parallelstore_instance('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_parallelstore_instance')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_parallelstore_instance,
    method: :google_parallelstore_instance,
    required_attrs: { capacity_gib: 'test-value', instance_id: 'test-value', location: 'test-value' },
    expected_outputs: [:id, :access_points, :create_time, :daos_version, :deletion_policy, :effective_labels, :effective_reserved_ip_range, :name, :project, :state, :terraform_labels, :update_time],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
