# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_billing_project_info resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GoogleBillingProjectInfo do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { billing_account: 'test-value' } }

  describe ':google_billing_project_info' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_billing_project_info('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_billing_project_info', 'test')
        validate_required_attributes(config, [:billing_account])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_billing_project_info('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_billing_project_info)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_billing_project_info('test', required_attrs)

        expect(ref.id).to eq("${google_billing_project_info.test.id}")
        expect(ref.project).to eq("${google_billing_project_info.test.project}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_billing_project_info('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_billing_project_info', 'test')
        expect(config).not_to have_key('project')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_billing_project_info('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_billing_project_info', 'typed')
        expect(config['billing_account']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_billing_project_info('first', required_attrs)
        synth.google_billing_project_info('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_billing_project_info')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_billing_project_info,
    method: :google_billing_project_info,
    required_attrs: { billing_account: 'test-value' },
    expected_outputs: [:id, :project],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
