# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a google_privateca_certificate_template resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GooglePrivatecaCertificateTemplate do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { location: 'test-value', name: 'test-value' } }

  describe ':google_privateca_certificate_template' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_privateca_certificate_template('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'google_privateca_certificate_template', 'test')
        validate_required_attributes(config, [:location, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_privateca_certificate_template('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:google_privateca_certificate_template)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.google_privateca_certificate_template('test', required_attrs)

        expect(ref.id).to eq("${google_privateca_certificate_template.test.id}")
        expect(ref.create_time).to eq("${google_privateca_certificate_template.test.create_time}")
        expect(ref.effective_labels).to eq("${google_privateca_certificate_template.test.effective_labels}")
        expect(ref.project).to eq("${google_privateca_certificate_template.test.project}")
        expect(ref.terraform_labels).to eq("${google_privateca_certificate_template.test.terraform_labels}")
        expect(ref.update_time).to eq("${google_privateca_certificate_template.test.update_time}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_privateca_certificate_template('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_privateca_certificate_template', 'test')
        expect(config).not_to have_key('create_time')
        expect(config).not_to have_key('effective_labels')
        expect(config).not_to have_key('project')
        expect(config).not_to have_key('terraform_labels')
        expect(config).not_to have_key('update_time')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', identity_constraints: [{ 'key1' => 'val1' }], labels: { 'key1' => 'val1' }, maximum_lifetime: 'test-value', passthrough_extensions: [{ 'key1' => 'val1' }], predefined_values: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_privateca_certificate_template('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_privateca_certificate_template', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('identity_constraints')
        expect(config).to have_key('labels')
        expect(config).to have_key('maximum_lifetime')
        expect(config).to have_key('passthrough_extensions')
        expect(config).to have_key('predefined_values')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_privateca_certificate_template('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_privateca_certificate_template', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_privateca_certificate_template('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_privateca_certificate_template', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes identity_constraints when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_privateca_certificate_template('opt', required_attrs.merge(identity_constraints: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_privateca_certificate_template', 'opt')
        expect(config).to have_key('identity_constraints')
      end

      it 'omits identity_constraints when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_privateca_certificate_template('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_privateca_certificate_template', 'minimal')
        expect(config).not_to have_key('identity_constraints')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_privateca_certificate_template('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_privateca_certificate_template', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_privateca_certificate_template('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_privateca_certificate_template', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes maximum_lifetime when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_privateca_certificate_template('opt', required_attrs.merge(maximum_lifetime: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_privateca_certificate_template', 'opt')
        expect(config).to have_key('maximum_lifetime')
      end

      it 'omits maximum_lifetime when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_privateca_certificate_template('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_privateca_certificate_template', 'minimal')
        expect(config).not_to have_key('maximum_lifetime')
      end
      it 'includes passthrough_extensions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_privateca_certificate_template('opt', required_attrs.merge(passthrough_extensions: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_privateca_certificate_template', 'opt')
        expect(config).to have_key('passthrough_extensions')
      end

      it 'omits passthrough_extensions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_privateca_certificate_template('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_privateca_certificate_template', 'minimal')
        expect(config).not_to have_key('passthrough_extensions')
      end
      it 'includes predefined_values when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_privateca_certificate_template('opt', required_attrs.merge(predefined_values: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_privateca_certificate_template', 'opt')
        expect(config).to have_key('predefined_values')
      end

      it 'omits predefined_values when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_privateca_certificate_template('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'google_privateca_certificate_template', 'minimal')
        expect(config).not_to have_key('predefined_values')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_privateca_certificate_template('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'google_privateca_certificate_template', 'typed')
        expect(config['location']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.google_privateca_certificate_template('first', required_attrs)
        synth.google_privateca_certificate_template('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'google_privateca_certificate_template')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :google_privateca_certificate_template,
    method: :google_privateca_certificate_template,
    required_attrs: { location: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :create_time, :effective_labels, :project, :terraform_labels, :update_time],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
