# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_compute_network_attachment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleComputeNetworkAttachment
    include Pangea::Resources::ResourceBuilder

    define_resource :google_compute_network_attachment,
      attributes_class: Google::Types::ComputeNetworkAttachmentAttributes,
      outputs: { id: :id },
      map: [:connection_preference, :name, :subnetworks],
      map_present: [:deletion_policy, :description, :producer_accept_lists, :producer_reject_lists, :project, :region]
  end
  module Google
    include GoogleComputeNetworkAttachment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
