# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/google_bigtable_table/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GoogleBigtableTable
    include Pangea::Resources::ResourceBuilder

    define_resource :google_bigtable_table,
      attributes_class: Google::Types::BigtableTableAttributes,
      outputs: { id: :id },
      map: [:instance_name, :name],
      map_present: [:automated_backup_policy, :change_stream_retention, :column_family, :deletion_policy, :deletion_protection, :project, :row_key_schema, :split_keys]
  end
  module Google
    include GoogleBigtableTable
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Google)
