# Code generated by pangea-forge.
# InSpec profile for verifying google_service_networking_connection infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GOOGLE_TOKEN and GOOGLE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/google_service_networking_connection/ -t google://

control 'google_service_networking_connection-exists' do
  impact 1.0
  title 'Manages a google_service_networking_connection resource'
  desc 'Verify that the google_service_networking_connection resource exists and has expected properties'

  describe google_service_networking_connection(name: attribute('id')) do
    it { should exist }
    its('network') { should_not be_nil }
    its('reserved_peering_ranges') { should_not be_nil }
    its('service') { should_not be_nil }
  end
end
